### ISSUE TITLE
react-router 0.13.2  Uncaught TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by krisskross** [rackt/react-router#1134] opened 2015-04-27 15:03 UTC
Hi

I'm getting an error when trying to render this simple page with react 0.13.0 and react-router 0.13.2. 

```js
var React = require('react');
var Router = require('react-router');
var Route = Router.Route;
var RouteHandler = Router.RouteHandler;

var App = React.createClass({
  render: function() {
    return (
      <div> </div>
    );
  }
});

var routes = (
  <Route handler={App} name="app" path="/">
  </Route>
);
Router.run(routes, function (Handler, state) {
  React.render(<Handler/>, document.getElementById('content'));
});
```
Chrome complains about the following line.

```js
var _classCallCheck = function (instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } };
```

The page renders fine if I remove react-router. Any ideas of what could be wrong?

Cheers,
-Kristoffer

**Comment by flexd** [comment] 2015-04-28 15:30
I am also having this problem, just following the most basic example.

**Comment by paulmillr** [comment] 2015-04-30 19:41
same shit. 0.13.3 broke our app.

**Comment by flexd** [comment] 2015-05-01 07:48
I have somehow made it work with 0.13.2. No idea what I did, it just suddenly stopped giving me the error. :confused:

**Comment by gaearon** [comment] 2015-05-01 23:52
Is there any chance you are using an old version of JSX transpiler that compiles `<Handler />` into `Handler()` instead of the correct `React.createElement(Handler)`?

**Comment by gaearon** [comment] 2015-05-01 23:58
@paulmillr 

>React-router doesn't work at all currently.

Can you please give the exact steps or a sample project to reproduce?
RR 0.13.2 for me (I'm testing with React 0.13 and Babel).

**Comment by gsanta** [comment] 2015-05-03 12:57
Same problem with react-router 0.13.3 and react 0.13.2.

**Comment by gaearon** [comment] 2015-05-03 21:20
@gsanta What JSX transpiler are you using?

**Comment by stowns** [comment] 2015-05-07 00:14
+1 using grunt-react

**Comment by paulmillr** [comment] 2015-05-07 00:24
we're using CJSX compiler.

**Comment by adjavaherian** [comment] 2015-05-09 00:10
Us too.  Specifically in our test suite, we have a test context which handles each component.  In the example below, ```targetComponent``` can be any old React Class.  Problem seems to be isolated to ```TestLocation``` in our case.

```javascript

// tests/TestContext.js
// used to bootstrap components that require flux
'use strict';

var Router = require('react-router'),
    Route = Router.Route,
    TestLocation = Router.TestLocation,
    FluxxorTestUtils = require('fluxxor-test-utils'),
    FluxConstructor = require('../../app/FluxConstructor.js');

var TestContext = {

    getRouterComponent: function(targetComponent, props) {
        var realFlux = FluxConstructor();
        var fakeFlux = FluxxorTestUtils.fakeFlux(realFlux);

        //check props and add flux
        if(typeof props === 'undefined'){
            props = {};
        }
        props.flux = fakeFlux;

        var component, mainComponent,
            routes = (
                <Route name="test" path="/" handler={targetComponent} />
            );

        //create router history
        TestLocation.history = ['/test'];

        //run router
        Router.run(routes, TestLocation, function (Handler) {

            //mainComponent = React.render(<Handler props={props} />, global.document.body);
            //component = TestUtils.findRenderedComponentWithType(mainComponent, targetComponent);

        });

        return {
            flux: fakeFlux,
            component: component,
            mainComponent: mainComponent,
            location: TestLocation
        };
    }
};

module.exports = TestContext;

```

Using 
└── babel@4.7.16 
└── react-router@0.13.3 

Trace: 

```sh
1) app/modules/HeaderNav.jsx renders the HeaderNav class:
TypeError: Cannot call a class as a function
at _classCallCheck (/Users/4m1r/xxxxxx/xxxxxx-web/node_modules/react-router/lib/locations/TestLocation.js:3:106)
at Function.TestLocation (/Users/4m1r/xxxxxx/xxxxxx-web/node_modules/react-router/lib/locations/TestLocation.js:17:5)
at Function.dispatchHandler (/Users/4m1r/xxxxxx/xxxxxx-web/node_modules/react-router/lib/createRouter.js:381:22)
at /Users/4m1r/xxxxxx/xxxxxx-web/node_modules/react-router/lib/createRouter.js:349:29
at /Users/4m1r/xxxxxx/xxxxxx-web/node_modules/react-router/lib/Transition.js:69:9
at Function.Transition.to (/Users/4m1r/xxxxxx/xxxxxx-web/node_modules/react-router/lib/Transition.js:72:15)
at /Users/4m1r/xxxxxx/xxxxxx-web/node_modules/react-router/lib/createRouter.js:348:22
at Function.Transition.from (/Users/4m1r/xxxxxx/xxxxxx-web/node_modules/react-router/lib/Transition.js:51:15)
at Function.dispatch (/Users/4m1r/xxxxxx/xxxxxx-web/node_modules/react-router/lib/createRouter.js:345:20)
at Function.refresh (/Users/4m1r/xxxxxx/xxxxxx-web/node_modules/react-router/lib/createRouter.js:396:16)
at Function.run (/Users/4m1r/xxxxxx/xxxxxx-web/node_modules/react-router/lib/createRouter.js:392:16)
at Object.runRouter [as run] (/Users/4m1r/xxxxxx/xxxxxx-web/node_modules/react-router/lib/runRouter.js:45:10)
at Object.getRouterComponent (/Users/4m1r/xxxxxx/xxxxxx-web/test/lib/TestContext.js:32:16)
at Context.<anonymous> (/Users/4m1r/xxxxxx/xxxxxx-web/test/app/modules/headerNav-test.js:26:62)
    at callFn (/usr/local/lib/node_modules/mocha/lib/runnable.js:266:21)
    at Test.Runnable.run (/usr/local/lib/node_modules/mocha/lib/runnable.js:259:7)
    at Runner.runTest (/usr/local/lib/node_modules/mocha/lib/runner.js:387:10)
    at /usr/local/lib/node_modules/mocha/lib/runner.js:470:12
    at next (/usr/local/lib/node_modules/mocha/lib/runner.js:312:14)
    at /usr/local/lib/node_modules/mocha/lib/runner.js:322:7
    at next (/usr/local/lib/node_modules/mocha/lib/runner.js:257:23)
    at /usr/local/lib/node_modules/mocha/lib/runner.js:284:7
    at done (/usr/local/lib/node_modules/mocha/lib/runnable.js:222:5)
    at callFn (/usr/local/lib/node_modules/mocha/lib/runnable.js:277:7)
    at Hook.Runnable.run (/usr/local/lib/node_modules/mocha/lib/runnable.js:259:7)
    at next (/usr/local/lib/node_modules/mocha/lib/runner.js:268:10)
    at Object._onImmediate (/usr/local/lib/node_modules/mocha/lib/runner.js:289:5)
    at processImmediate [as _immediateCallback] (timers.js:354:15)

```

**Comment by gaearon** [comment] 2015-05-09 22:47
@paulmillr Do you use `coffee-react` >=3.0?

**Comment by gaearon** [comment] 2015-05-09 22:52
To anybody having this problem: please, can you extract a reproducible example? It's hard to say what's going on because on my projects, and in examples, everything works fine. It's hard to guess by code snippets.

**Comment by gaearon** [comment] 2015-05-09 23:06
@adjavaherian 

In your example, `TestLocation` is used incorrectly. It should be created individually for each test:

```js
var location = new TestLocation([ '/test' ]);
Router.run(routes, location, function (Handler) {
  ...
});
```

It should *not* be used directly like in your example:

```js
Router.run(routes, TestLocation, function (Handler) { // wrong
```

If the code that sets fields directly on `TestLocation` worked before, it was pure luck. It's true that the docs are lacking on it, please feel free to send a PR :-). Personally I think it might be better to export factories (`createTestLocation` and `createStaticLocation`) to prevent these kinds of mistakes. (cc @mjackson who's working on the new API)

**Comment by adjavaherian** [comment] 2015-05-10 00:58
Thanks @gaearon that helps, so I no longer get the class issue, but now I'm seeing a makeHref issue.  

```javascript
        var component, mainComponent,
            routes = (
                <Route name="test" path="/test" handler={targetComponent} />
            );

        //create router history
        var location = new TestLocation(['/test']);

        //run router
        Router.run(routes, location, function (Handler) {
            mainComponent = React.render(<Handler props={props} />, global.document.body);
            component = TestUtils.findRenderedComponentWithType(mainComponent, targetComponent);

        });

```


These warnings too

```javascript
  app/modules/HeaderNav.jsx
Warning: Failed Context Types: Required context `router` was not specified in `Link`.
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `function (props, context) {
      // This constructor is overridden by mocks. The argument is used
      // by mocks to assert on what gets mounted.

      if ("production" !== process.env.NODE_ENV) {
        ("production" !== process.env.NODE_ENV ? warning(
          this instanceof Constructor,
          'Something is calling a React component directly. Use a factory or ' +
          'JSX instead. See: http://fb.me/react-legacyfactory'
        ) : null);
      }
```

I haven't upgraded this to RR13 yet, but this repo shows the whole test suite I'm using.  If you wanna try forking that and upgrading it to 13.  https://github.com/adjavaherian/mocha-react

**Comment by gaearon** [comment] 2015-05-10 10:33
@adjavaherian 

[This guide](https://github.com/rackt/react-router/blob/master/docs/guides/testing.md) describes the `contextTypes` problem you're having, as well as the solution to it.

**Comment by Mosho1** [comment] 2015-05-11 18:19
I'm having this issue as well.

`React.CreateElement` has this line:

`return type.apply(null, Array.prototype.slice.call(arguments, 1));`

Where `type` is `require('react-router').Route`, or the following function:

    function Route() {
        _classCallCheck(this, Route);
        if (_React$Component != null) {
          _React$Component.apply(this, arguments);
        }
      }

the context of this call is clearly `null`, which makes `_classCallCheck(this, Route);` throw.

**Comment by gaearon** [comment] 2015-05-11 18:35
>React.CreateElement has this line:
>return type.apply(null, Array.prototype.slice.call(arguments, 1));

As far as I can see [React 0.13 doesn't contain such a line](https://github.com/facebook/react/blob/v0.13.0/src/classic/element/ReactElement.js#L149-L201). On the other hand, [React 0.12 contains it](https://github.com/facebook/react/blob/v0.12.2/src/core/ReactLegacyElement.js#L191).

Which is why the current version of the router requires React 0.13. Are you sure you're using it?

**Comment by Mosho1** [comment] 2015-05-11 19:03
That did it, thanks! Not sure why I had an older version.

**Comment by gaearon** [comment] 2015-05-11 19:10
If you have this issue you're either:

* Using an old React version (must be >= 0.13)
* Using an old JSX compiler (must be compatible with React >= 0.13)
* Incorrectly using `TestLocation` (see the [fix above](https://github.com/rackt/react-router/issues/1134#issuecomment-100559235))

I'm closing this issue.
If you have a reproducible example of this problem, please share it with us so we can take a look!

**Closed by gaearon** 2015-05-11 19:10 UTC

**Comment by toshi0383** [comment] 2015-05-24 09:12
How can I figure out which jsx compiler version I am using ?
I have this issue reproduced right now.
My package.json dependency:

```
  "dependencies": {
    "express": "~3.3.4",
    "reactify": "~0.14.0",
    "react": "0.13",
    "parse": "*",
    "react-router": "0.13.3",
    "uglify-js": "~2.4.15"
  }
```

```
    var App = React.createClass({displayName: 'App',
      render: function() {
        return (
          React.DOM.div(null,
            NavigationBar(null),
            RouteHandler(null)
          )
        );
      }
    });

    var routes = (
      Route({name: "app", path: "/", handler: App},
        Route({name: "login", path: "/login", handler: LoginBox}), // ERROR
        Route({name: "signup", path: "/signup", handler: SignUpBox}),
        Route({name: "session", path: "/session", handler: EventBox}),
        DefaultRoute({handler: EventBox})
      )
    );
```

**Comment by gaearon** [comment] 2015-05-24 10:29
@toshi0383 You are using a very old version of `reactify`. Switch to 1.x and you'll be fine.

**Comment by toshi0383** [comment] 2015-05-24 11:43
Thanks, it worked !

**Comment by blainegarrett** [comment] 2015-12-22 18:27
I ran into the same issue while working through a node server + react-router example. In that case, server.js was calling node-jsx.install(). I was running 0.2 of node-jsx (from the isomorphic-react example). Upgrading to 0.13.3 fixed the issue. 

A generic tl;dr to this issue is "upgrade your jsx transpiler".
