### ISSUE TITLE
Feedback on 1.0.0 API: <Link> element should not be aware of the exact path

### ISSUE THREAD

**Issue by jlecomte** [rackt/react-router#1791] opened 2015-08-31 18:36 UTC
I noticed that one of the changes between 0.13.x and 1.0.0-beta3 is the way the `<Link>` element works. According to the docs, it seems like in 1.0.0-beta3, a `<Link>` element must be aware of the exact structure of a route. However, in 0.13.x, `<Link>` elements could simply refer to a route's name, passing only the necessary values defined in that route's placeholders. I much prefer the old API because it makes it easier to change a path, if needed.

**Comment by igl** [comment] 2015-08-31 18:41
Cool URIs don't change.

**Comment by jlecomte** [comment] 2015-08-31 18:46
@lgl If you don't ever need to change your application routes, using either API should not matter. However, if you do find yourself having to update your application routes, the 0.13.x API makes that task much simpler since you only need to change code in one place.

**Comment by jlecomte** [comment] 2015-08-31 19:08
Ideally, the `<Link>` element could support both modes. For example, Yahoo's fluxible-router supports:

`<NavLink href='/users/123'>` (you take care of generating the actual path - more readable)

and

`<NavLink routeName='user' navParams={{id: 123}}>` (the system generates the path, less readable but more dynamic)

**Comment by igl** [comment] 2015-08-31 19:17
I am not sure about the exact motive why it was removed. Probably to remove complexity and free the Link component from being connected a global route list.

You can still save a map of your URLs in a constant file somewhere. `<Link to={URLS.home} />
or use a i18n-like function `getURL('home')`

Simple and nice.

**Comment by jdelight** [comment] 2015-09-01 21:07
@jlecomte I noticed this too: https://twitter.com/jamesdacosta/status/618524445351768064

**Comment by steevel** [comment] 2015-09-02 21:01
This is a pain when developing a new app, we're changing our URIs a lot at the moment. I also thought one of the reasons behind actually having a "name" for each route was to easily do i18n, I guess we need to maintain duplicates of all routes, one per language now. Names being global was one of the things I liked about them :-)

**Comment by Syynth** [comment] 2015-09-03 02:31
I can't help but agree the removal of these is irksome, but I believe this is more or less a duplicate of this issue: https://github.com/rackt/react-router/issues/1514

@igl As far as I could tell from reading #1514 the reason it's being removed is to support code splitting.

Personally I would love this feature stay around and do one of two things
1) Loudly disclaim that `<Link to="name-of-route: />` will probably not work if you use code splitting
or
2) Provide some guarantee that named routes will at least work within a single bundle. Names could be unique withing a single bundle, and in order for one bundle to link to another, it would just use an actual URL

I guess 2 would just also include the disclaimer from 1, but more specific.

**Comment by ryanflorence** [comment] 2015-09-06 18:17
I'm hoping somebody wraps `<Link/>` with a new component that supports named routes, if not, I'm sure I'll get around to it eventually, but its a convention we don't want to prescribe in the API.

> must be aware of the exact structure of a route

I personally have no more or less difficulty with either of these:

```js
<Link to={`/courses/${course.id}/assignments/${assignment.id}`}/>
<Link to="courses.assignments" params={{ courseId: course.id, assignmentId: assignment.id }}/>
```

I had to look at the route config to know the name of the route **and** the names of the parameters. Paths are IDs just like names, no need for the router to duplicate here.

I get that its a convenience many people enjoy, so again, I'm hoping somebody makes `react-router-named-routes` and creates a `Link` and a `Navigation` mixin that understand named routes. I don't think it would be too bad.

**Comment by jlecomte** [comment] 2015-09-06 19:05
I understand why people disagree with using named routes. However, my point here is that it would be great if react router could support both named routes and static routes. Then, it is up to the developer to choose. Early in the life of a project, being able to easily change the routes definition can be useful.

**Comment by ryanflorence** [comment] 2015-09-06 19:36
> Early in the life of a project, being able to easily change the routes definition can be useful.

Absolutely, that's why I hope somebody wraps Navigation and Link to facilitate this.

**Comment by mjackson** [comment] 2015-09-07 15:38
We're not saying you *can't* use named routes or that you'll never be able to ever again, @jlecomte. What we *are* trying to do with 1.0 is figure out the right primitives so that users are more free to build and extend on top of what we give you.

In the case of `<Link>`s, we believe the right primitives are `pathname`, `query`, and `state`. If a `<Link>` provides us those three pieces of information we know how to create URLs and tell if a `<Link>` is active or not.

When @ryanflorence says he hopes somebody wraps the API, what he means is doing something like this:

```js
const RouteNames = {
  home: '/path/to/home'
}

class NamedLink extends React.Component {
  render() {
    return (
      <Link to={RouteNames[this.props.name]} />
    )
  }
}
```

It's much easier for users to build stuff like this on top of our API if we focus on providing the right primitives instead of prescribing these APIs for you.

Anyway, we've said all of this before in #1514, but it seems to be falling on deaf ears. I'm going to close this issue as a duplicate.

**Closed by mjackson** 2015-09-07 15:38 UTC

**Comment by mjackson** [comment] 2015-09-07 15:57
Let's follow up post 1.0 in #1840
