### ISSUE TITLE
Cannot read property 'isActive' of undefined - when testing a component that uses Router.State mixin

### ISSUE THREAD

**Issue by praveenaj** [rackt/react-router#1973] opened 2015-09-16 06:02 UTC
I'm testing a React component in which I have used Router.State mixin to call `isActive`. To do this I'm trying to stub isActive to return true but to no avail.

Test error:
```
 TypeError: Cannot read property 'isActive' of undefined
```

Component
```
'use strict';

var MyComponent = require('MyComponent.jsx'),

    React = require('react/addons'),
    ReactTestUtils = React.addons.TestUtils,

    sinon = require('sinon'),
    expect = require('chai').expect;


describe('Test Component', function() {

  before(function () {

    sinon.stub(MyComponent.prototype,'isActive').returns(true);
    this.component = ReactTestUtils.renderIntoDocument(
      <MyComponent />
    );

  });

   it('should render MyComponent component', function(){
    expect(this.component).toBeDefined();
  });


});
```

**Comment by prattsj** [comment] 2015-09-16 06:26
Possibly a duplicate of #1936?

If you're using react-router 1.0.x, you'll want to switch to using the History mixin. See the discussion in #1936.

Other resources:
- [History mixin docs](https://github.com/rackt/react-router/blob/master/docs/api/History.md)
- [Upgrade guide section on the old State mixin](https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md#state-mixin)

**Closed** 2015-09-17 12:54 UTC
