### ISSUE TITLE
ES6 usage in documentation

### ISSUE THREAD

**Issue by Download** [rackt/react-router#2561] opened 2015-11-17 15:09 UTC
Maybe this is me being daft, but is there an error in [the docs for server side rendering](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md)?

I see this:

```js
match({ routes, location: req.url }, 
```

Is this valid JS?

Does it create a key `routes` on the object with value `undefined`? Or is this ES6 syntax perhaps?

If indeed an error, can we fix this as server-side rendering docs are so scarce atm?

**Comment by Download** [comment] 2015-11-17 15:21
Mmm ok so I read the actual code... above syntax seems to be correct. I think it's called *destructuring*...

However because ES6 is still so new, it might be a good idea to spend a comment on this or provide a version in ES5 syntax as well.

**Comment by taion** [comment] 2015-11-17 15:36
But that exact example is also using ES6 modules. And arrow functions. Maybe we should have a top-level link to some sort of ES6 reference instead?

**Comment by taion** [comment] 2015-11-17 15:37
I updated the title of the issue with a better summary of the problem at hand. Looking for feedback here.

**Comment by Download** [comment] 2015-11-17 15:48
Yes you are right. Entire example is in ES6. So in that sense it is ok.

However, maybe we need to look at this differently. Let me explain my use-case...

I am trying to do server-side rendering from a Java web application. Java has the Nashorn JS interpreter built-in and React runs fine on that. However Nashorn does not have `require` and also (I think) no ES6 (yet). 

In general I think that maybe, for the server-side part, it would be better not to depend on 'advanced' features such as `require` / `import` and ES6 in particular but keep it simpler so it will work on more platforms.

Also, the current example assumes a Javascript webserver, but I would love to see a version of this which doesn't try to handle redirect and 404 etc itself but instead let's the caller take care of it.

**Comment by Download** [comment] 2015-11-17 15:51
Also see [this issue](https://github.com/facebook/react/issues/5490) which is part of the problems I am facing trying to implement server-side rendering on Java. Because there is no require I load the pre-bundled React but some stuff I need is not exposed then...

**Comment by taion** [comment] 2015-11-17 16:27
Broadly, I don't think it's a good fit here to gear the documentation toward people who aren't using Node.

It is dramatically, dramatically easier to build something viable if you use a Node server for SSR, and separate SSR from your actual API servers. You're following a path that more people have used, configuration is simpler, and it's just easier overall.

I don't want to dismiss what you're attempting to do, but I think trying to document SSR on non-Node platforms is out of scope - I'm not aware that any of the maintainers on this project use those platforms, and we'd have a very difficult time keeping such documentation up-to-date.

**Comment by BerkeleyTrue** [comment] 2015-11-17 16:47
ES2015 is now JavaScript. These are not 'advanced' features, they are just syntax of the language. The language is evolving. We shouldn't be blacklisting features in documentation because they are not available in platform X.

It should be up to the developer to figure out what version of JS to use in the platform of their choice. Otherwise we would be stuck only ever mentioning features available in IE9.

Also considering that JS has moved to a yearly release cycle. Meaning, every year an update will adopt new syntax into the language.

**Comment by taion** [comment] 2015-11-17 17:18
I agree, and I don't think we should have all of our examples in both ES5 and ES6.

However, given that e.g. the documentation on http://facebook.github.io/react/ doesn't use ES6 at all, there is a decent chance that we're the first stop for developers who have not yet onboarded onto ES6.

Given that, I think a low-cost way of approaching this would be to add a note somewhere linking to a good ES5 -> ES6 transition guide, just to point users in the right direction

Where and which? I don't know.

**Comment by timdorr** [comment] 2015-11-17 17:48
Where? [Here.](https://github.com/rackt/react-router/blob/master/docs/Introduction.md)

Which? [Here.](https://github.com/lukehoban/es6features#readme)

**Comment by taion** [comment] 2015-11-17 18:08
:+1:

**Comment by ryanflorence** [comment] 2015-11-17 19:35
Agree to just link to something but I doubt it will make these issues go away.

ES_2015_SPEC.pdf in the repo?!

**Comment by mjackson** [comment] 2015-11-17 19:52
Part of me thinks we should just write all our docs/examples in ES5. The
router is popular enough that many people are coming to it who aren't
familiar with the latest babel tricks. As one of the core projects of the
React ecosystem, it would be great if we could avoid discussing this kind
of thing here and just follow the lead of the React docs.

**Comment by taion** [comment] 2015-11-17 20:06
@ryanflorence I don't think we can make these issues go away, but at least pointing our users to the ES6 guide would be an improvement.

@mjackson I share that concern. I think there's a practical problem where none of the collaborators on this project (I think) use ES5 any more, so there's additional risk of the code in the relevant docs/examples going stale or just being wrong (e.g. from having syntax errors). Hard to say - it'd definitely feel a bit unpleasant to have to drop back into ES5 for writing docs.

**Comment by Download** [comment] 2015-11-17 20:20
Sorry for triggering such a debate lol.

I do think that, as far as server-side rendering goes, ES6 can be called 'advanced' in the sense that there is very little support for it. That will take some more time I guess. Java is pretty big on the server but I did not succeed in getting Nashorn to cooperate with this so I'm stuck on ES5 I think.

Just to put things in perspective, what I am currently doing to get my React code to run is using Gulp + Browserify + Babel to 'compile' it to ES5, then copy-pasting the resulting output to my Java project... Not my dream setup.

What I would love is for a more complete example of server-side rendering. Now we have to grab bits from everywhere... Actually I think this document at the react-router docs is at this moment the best resource (as in up-to-date and adresses the actual routing that is of course important to render the right thing) so please take my comments as constructive.  :)  

As long as you do server-side rendering from Node the whole Browserify / Babel / Webpack thing works (kinda, its'not so easy to set up I think) but when you want to do it from a non-Node JS platform it becomes unworkable.

**Comment by taion** [comment] 2015-11-17 20:22
The issue is that using a non-Node platform is the advanced, special use case - one that I don't think we can reasonably support to the same extent as with Node.

I understand that it's difficult to do SSR without Node, but that difficulty comes from the relevant tech stack being an unusual and specialized one, as opposed to the much more common Node-based stack.

**Comment by Download** [comment] 2015-11-17 20:22
> Broadly, I don't think it's a good fit here to gear the documentation toward people who aren't using Node.

Well that is at least a very clear distinction to make... I am not on Node so this doc would not be for me then.

I do wonder why you would take this stance though? There is no inherent magic in react-router that requires Node right?

**Comment by taion** [comment] 2015-11-17 20:24
No, but it's simply the case that almost everyone uses Node. Take a look at e.g. the upstream SSR examples: https://facebook.github.io/react/blog/#two-packages-react-and-react-dom. The availability of CJS modules (and a JSX transpiler) is taken for granted. If you're not in a CJS environment, you're doing something very unusual.

**Comment by Download** [comment] 2015-11-17 20:24
> The issue is that using a non-Node platform is the advanced, special use case

That's only true when reasoning from the prespective of react-router.

Looking at it from the perspective of the webdeveloper I wouldn't call Java EE advanced or special. It's commodity. It's one of the dominant server technologies.

**Comment by Download** [comment] 2015-11-17 20:26
> but it's simply the case that almost everyone uses Node.

This is simply not true.

Java EE is still much more widely used then Node, though it is gaining fast. Maybe 'almost everyone that uses react-router uses Node', but this is a self-sulfilling prophecy if you gear all the docs towards Node isn't it?

**Comment by taion** [comment] 2015-11-17 20:26
Yes - I'm aware of that. In fact my entire actual backend is on Python with Flask. I imagine a majority of the other collaborators on this project who are working full-stack also do not have Node-based backends.

The unusual thing is using a platform other than Node to handle the server-side rendering piece; the most common setup is to deploy your backend API in your platform of choice, then use a Node server to handle isomorphic rendering.

**Comment by Download** [comment] 2015-11-17 20:28
But what if you already have a backend?

Anyways I think the discussion about whether or not we should use Node is a bit offtopic, *unless* react-router team decides they have no interest is supporting other platforms.

**Comment by timdorr** [comment] 2015-11-17 20:31
I've found most Java EE devs are stuck on legacy code that can't make use of a library just released last week. So, you're lucky! :smile:

We certainly *support* other platforms when it comes to the code itself. You're free to use this library inside of Nashorn or other crazy platforms. But the documentation needs to be written around a specific platform, and the vast majority of readers are going to be using Node.

**Comment by Download** [comment] 2015-11-17 20:32
Guys I'm not going to install Node on my (Openshift, costs me an extra Gear too) backend, so I am going ahead with trying to get this to work.

What I will do is see if I can set up a simple repo with a working Hello World example with react-router in it. Then maybe we can link to that for future Java devs looking for examples.

**Comment by taion** [comment] 2015-11-17 20:36
You're very welcome to put together such an example, and I hope others working with Java EE backends find it helpful in the future. As you can see, we've also worked with e.g. library writers working in the Rails ecosystem to give them the hooks for solving their use cases: https://github.com/rackt/react-router/issues/1777

The issue remains that almost everyone who is doing server-side rendering with React is running a Node server to do so, which means that has to be the primary platform we target and support. It's the platform that we all use for server-side rendering, before fanning out to our respective actual backends in a variety of languages.

React Router doesn't care at all what backend you use, but it's important to note that in general, SSR is not the same concern as backend API, and the typical approach is to deploy a separate Node server to handle SSR.

I'm going to leave this issue open for now until we get that ES6 note added, or until we decide to use ES5 for all code examples in documentation. I don't think there's any circumstance in which we'd drop the assumption of a CJS environment (i.e. Node or an equivalent) from our examples and documentation for server-side code, though.

**Comment by timdorr** [comment] 2015-11-17 20:37
I think a separate repo that demos usage with es5 or UMD or other esoteric means of using the library would be great. 

The implementation details are outside of the scope of the docs anyways. Should we add SSR docs alongside Express for Koa, Hapi, etc etc? Probably not. But someone can certainly show an example of it and we can link to it in some capacity. We need an `awesome-react-router` anyways :)

**Comment by timdorr** [comment] 2015-11-17 20:42
@taion [Done](https://github.com/rackt/react-router/commit/5c0f661982846666d18135ea2552f035bf4ea1ff)

**Closed by timdorr** 2015-11-17 20:42 UTC
Labels: discussion, docs
