### ISSUE TITLE
Routing and Layering

### ISSUE THREAD

**Issue by zoomclub** [rackt/react-router#551] opened 2014-12-01 07:45 UTC
Using Z layers is an important feature in modern apps and a logical addition to routing, so that all aspects of layout (nesting and layers) are covered. Is it possible to add layers to components and manage them with react-router to complete all my design dreams?

**Comment by cmwelsh** [comment] 2015-01-17 03:02
This seems like this is a duplicate of #266.

I currently have a UI like this that I'm rendering "manually":

http://instagram.com/github

Notice how the URL changes when you click a photo from the list and the details view is rendered in a modal. However, the background stays rendered as well.

**Comment by zoomclub** [comment] 2015-01-18 08:40
The modal dialog and offcanvas approaches are both popular and represent ways of layering divs. This can work for some of what I'm going for but is not then an integrated solution for react-router. 

I'm thinking more along the lines of defining react components for each class of editor used in the app. These components contain all their sub-components and react-router is the right solution for managing the layout within each of these editor class components. 

Essentially, there are the bigger editor components then with inner sub-components that are reused and fed different data per use case and an onboard react-router is perfect for managing the layout and morphing of the sub-components into alternate layouts.

That part works fine. Now we want to work these component editors into layers. Maybe its just easier to create a simple var with an array of these editors and a function to hide, show, blend, send to back, bring to front the editors plus manage nice animations as the layers are transitioned? It would be straightforward, basically having a stack of editors much like there is often a stack of canvases in drawing apps.

**Comment by zoomclub** [comment] 2015-01-18 08:52
Apparently I unintentionally closed this issue, that was not the intent :)

**Comment by cmwelsh** [comment] 2015-01-19 16:16
You probably clicked Comment and Close instead of Comment.

**Comment by zoomclub** [comment] 2015-01-19 17:30
Thanks for letting me know, I'll reopen it for further discussion then. I came across the following demo yesterday that is related to the the kind of layering of components I'm hoping to achieve. It has its own little router, see the code here:

http://coenraets.org/blog/2014/12/animated-page-transitions-with-react-js/

**Comment by irvinebroque** [comment] 2015-01-26 18:13
Encountering this today, and I think exposing a way to get the "depth" of a given route would solve a lot of this, without React-Router actually managing z-index directly.

For example, let's say I have the following route config, where the `New Message` route is a modal:

    <Route name="App" path="/" handler={App}>
      <Route name="Messages" path="messages" handler={Messages}>
        <DefaultRoute name="Overview" handler={Overview}/>
        <Route name="New Message" path="new" handler={New}/>
      </Route>
    </Route>

Within the `New Message` component, I'd love to be able to write something like:

`this.getRouteDepth()`

Which would return `3`, because the `New Message` route is nested 3 levels deep. If `this.getRouteDepth()` was called inside of the `App` component, it would return `1`. These numbers could be easily mapped to any arbitrary z-index values.

Right now, here's what I do:

      // Z-Index management
      var depth;

      this.props.routerState.routes.forEach(function(route, index, array) {
        console.log(route)
        if (route.name === this.props.routeName) {
          depth = index;
        }
      }.bind(this))

      // Use depth to set z-index on the route
      console.log(depth);

This requires that I pass down a string for `this.props.routeName` to my view wrapper component, and this string must exactly match what comes back from the router's state object. It makes changing the names of routes brittle, because they need to be updated in two places.

**Comment by natew** [comment] 2015-01-27 04:18
If you use the RouteHandler mixin, you have a `getRouteDepth` function available:

https://github.com/rackt/react-router/blob/808669883f61e42a277c7728bcbe0bff0dab1f90/modules/RouteHandlerMixin.js

**Comment by mjackson** [comment] 2015-01-27 05:25
@irvinebroque awesome, you even chose the same function name as one we already have ;)

see @natew's comment! :D

**Comment by irvinebroque** [comment] 2015-01-27 08:01
Clearly I haven't been paying close enough attention to the upcoming release, I had no idea. Well done!

**Comment by rpflorence** [comment] 2015-02-01 03:25
With `getRouteDepth`, you can do z-indexing as well as decide which "layer" (I call them portals) to render to if that's what you're doing, you'll have to wrap the `RouteHandler` in the loving embrace of the context its going to need to work, but you could do it.

Please holler to reopen if I'm wrong :)

**Closed by rpflorence** 2015-02-01 03:25 UTC

**Comment by zoomclub** [comment] 2015-02-01 05:29
Its been an exciting week with react and also web audio conferences this week, much on the horizon! Glad to hear of the added layer support in react-router. Layers are practical and fun, saw this nice inspirational layer implementation last week: 

http://stas-melnikov.ru/layered_responsive_modal_window/
