### ISSUE TITLE
API document for replaceWith()?

### ISSUE THREAD

**Issue by hezjing** [rackt/react-router#752] opened 2015-02-01 19:46 UTC
Hi

I couldn't find the API documentation for `replaceWith()`, which is used in https://github.com/rackt/react-router/blob/master/examples/auth-flow/app.js#L92

Is this the React Router's API?

**Comment by gaearon** [comment] 2015-02-01 20:10
It's in `Navigation` mixin.

https://github.com/rackt/react-router/blob/master/docs/api/mixins/Navigation.md#replacewithroutenameorpath-params-query

Closing this, feel free to reopen if doesn't work out for some reason!

**Closed by gaearon** 2015-02-01 20:10 UTC

**Comment by hezjing** [comment] 2015-02-01 20:29
It looks like the `replaceWith()` does not work with route name. For example,
```
<Router name="inbox" path="inbox" handler="..."/>
```
and the following does not work,
`this.replaceWith('inbox')`

but this works,
`this.replaceWith('/inbox')`

**Comment by gaearon** [comment] 2015-02-01 22:48
Interesting, it works for me. Can you put up a reproducible example?
