### ISSUE TITLE
transitionTo("/absolute/path/?query") removes the ? when a trailing slash is present

### ISSUE THREAD

**Issue by appsforartists** [rackt/react-router#1192] opened 2015-05-14 01:05 UTC
As shown in the docs, `transitionTo` is intended to support paths with query strings:

```
router.transitionTo('/users/10?showAge=true');
```

However, if you add a trailing slash:
```
router.transitionTo('/users/10/?showAge=true');
```

The router will remove the `?` (causing a failure):
```
/users/10/showAge=true
```

#1148 reports a similar issue, but @taurose discounted it because the query in that issue was specified both as a string and a dictionary.

**Comment by appsforartists** [comment] 2015-05-14 23:34
In React 0.13.x, this appears to be caused by this line in PathUtils.injectParams:

```javascript
.replace(paramInjectTrailingSlashMatcher, '/');
```

@mjackson has refactored that function in HEAD, but I'm still experiencing the error.

**Comment by appsforartists** [comment] 2015-05-14 23:41
Based on the variable name, I'm guessing the goal is to make sure that this path:

```
/path/to/route/?
```

creates this URL:

```
/path/to/route/
```

If that's the case, perhaps your `/?` test should be `/?$` to ensure that you aren't replacing a query string.

**Comment by mjackson** [comment] 2015-06-19 13:53
Pretty sure this is a duplicate of #1148. Let's follow up there.

**Closed by mjackson** 2015-06-19 13:53 UTC
Labels: bug
