### ISSUE TITLE
Prevent caching component when params and query changed

### ISSUE THREAD

**Issue by trungpham** [rackt/react-router#800] opened 2015-02-09 10:42 UTC
It seems like the component is cached when the path is unchanged even though params and query have changed.
It should also invalid the cached component cache too if params and query have changed. This way the getInitialState callback will run when the params or query changed.

**Comment by gaearon** [comment] 2015-02-09 11:07
I think this is a duplicate of #793.

Router acts just like normal React components: if parent state (params/query) changes, re-mounting of children doesn't occur. You are free to handle it in `componentWillReceiveProps`.

So you should either use `componentWillReceiveProps` or manually add `key` based on route to force re-mounting.

See also: https://github.com/rackt/react-router/blob/master/docs/guides/overview.md#important-note-about-dynamic-segments

Does this answer your question?

**Comment by trungpham** [comment] 2015-02-09 18:01
Implementing the componentWillReceiveProps worked. Though, it feels a bit
strange that instead of reading from the nextProps, it's reading from
this.getParams(). :)

**Comment by gaearon** [comment] 2015-02-09 18:28
>it feels a bit strange that instead of reading from the nextProps, it's reading from this.getParams(). :)

I know it's weird :-). It's because we're using (undocumented) `this.context` and I'm not sure how it relates to lifecycle hooks. You can always pass `state` you get from `Router.run` callback explicitly to `RouteHandler` and down the hierarchy—this way you can read `params` from `nextProps`—no magic.

Closing!

**Closed by gaearon** 2015-02-09 18:28 UTC

**Comment by trungpham** [comment] 2015-02-10 00:00
Thank you for the detailed explanation. We should consider including the
dynamic segment disclaimer in the main README file. It can save future
developers a lot of time. :)
