### ISSUE TITLE
query object can't be found in server side render

### ISSUE THREAD

**Issue by fantasy8-me** [rackt/react-router#2001] opened 2015-09-18 06:50 UTC
Version: 1.0.0-rc1
Accessing following url 'http://localhost:4545/login?return=%2Fupload' from both server side and client side

And then use `this.props.location.query` to get query object

Client Side: return `{return: '/upload'}`, as expected

Server Side:  return `undefined`, and when print out the `this.props.location`, seems the query is stored in state. 
```
this.props.location.query { pathname: '/login',
  search: '',
  hash: '',
  state: { return: '/upload' },
  action: 'POP',
  key: null }
```

**Comment by acdlite** [comment] 2015-09-18 07:34
Thanks for reporting the issue! This is a duplicate of https://github.com/rackt/react-router/pull/1944. Let's track it over there :)

**Closed by acdlite** 2015-09-18 07:34 UTC
