### ISSUE TITLE
Wrapper routes doesn't work anymore

### ISSUE THREAD

**Issue by tarjei** [rackt/react-router#867] opened 2015-02-24 13:46 UTC
Hi

I like to use a wrapper around my components to separate state and rendering. Often it looks like this:

```jsx

            <Route name="inbox" path="/inbox" handler={InboxPage}>
                <Route name="inbox-first-message" path="" handler={InboxEntry} />
                <Route name="inbox-new" path="/inbox/new" handler={NewMessage} />
            </Route>
```

Now, after upgrading from 0.12.0 to 0.12.2 this seems not to work anymore. It seems that the components inside the wrapper components are not executed anymore. Is there a way around this problem?

In the code above, if I navigate to /inbox, RR wil not render the inbox-first-message component anymore.

**Comment by browniefed** [comment] 2015-02-24 15:26
@tarjei it looks you need to provide a `DefaultRoute` to tell it to render `inbox-first-message`
The empty path seems like a hack.

**Comment by tarjei** [comment] 2015-02-24 16:44
@browniefed I reited that too:

```
            <Route name="inbox" path="/inbox" handler={getPage("InboxPage")}>                
                <Route name="inbox-new" path="new" handler={getPage("NewMessage")} />
                <DefaultRoute name="inbox-first-message"  
                    
                    handler={getPage("InboxEntry")} />
            </Route>

```

**Comment by browniefed** [comment] 2015-02-24 16:47
@tarjei check out in the docs how `DefaultRoute` works.
[https://github.com/rackt/react-router/blob/master/docs/api/components/DefaultRoute.md](https://github.com/rackt/react-router/blob/master/docs/api/components/DefaultRoute.md)

You still keep the 2 `Route`s you just add an additional `DefaultRoute` with the handler `InboxEntry`

**Comment by tarjei** [comment] 2015-02-24 16:53
@browniefed it seems that it works if I do not give the DefaultRoute element a name. I'll have to research this more tomorrow.

**Comment by browniefed** [comment] 2015-02-24 16:55
@tarjei yes, `DefaultRoute` just tells it which handler to direct to. You do not give `DefaultRoute` a name.
```
            <Route name="inbox" path="/inbox" handler={InboxPage}>
                <Route name="inbox-first-message" handler={InboxEntry} />
                <Route name="inbox-new" path="/inbox/new" handler={NewMessage} />
                <DefaultRoute handler={InboxEntry} />
            </Route>
```

Ultimately your code would look something like the above

**Comment by taurose** [comment] 2015-02-24 17:35
> it seems that it works if I do not give the DefaultRoute element a name. I'll have to research this more tomorrow.

I think you're right. Seems like a bug with the recent changes to route creation and matching, treating DefaultRoute like a normal Route and using the name as its path instead of only using the parent's path.

**Comment by tarjei** [comment] 2015-02-24 17:45
OK, I updated the issue title accordingly.

**Comment by mjackson** [comment] 2015-02-24 21:42
@tarjei Sorry for the regression :/

It should be fixed in aef0dce5b3ff3ab27f968694670ea13c68c711a6, released in version 0.12.3 (with a test this time!) :)

**Comment by tarjei** [comment] 2015-02-25 05:50
@mjackson: Thanks, I'll test it later today.

**Comment by tarjei** [comment] 2015-02-25 07:29
Hi, the fix seems to work. One last question, is it possible to nest DefaultRoutes?

**Comment by mjackson** [comment] 2015-02-25 14:07
@tarjei No, a `<DefaultRoute>` can't have children. If you feel like you need that, you probably just want to nest another `<Route>`.

Glad we were able to get this fixed. And thank you for bringing it to our attention! :)

**Comment by tarjei** [comment] 2015-02-25 14:10
@mjackson grr. Ok. It is very useful to be able to use "empty" routes to inject wrappers around another handler as this makes it possible make the main rendering component not handle state + I can share code between components (think the code for loading div objects before rendring either the edit or the view component).

**Comment by mjackson** [comment] 2015-02-25 14:30
@tarjei What I mean is that if you have a `<DefaultRoute>` and you feel like it needs children, you should probably just make it a regular `<Route>`, e.g.

```xml
<Route handler={App}>
  <DefaultRoute handler={Dashboard}/>
</Route>
```

becomes

```
<Route handler={App}>
  <Route handler={Dashboard}>
    <DefaultRoute handler={Inbox}/>
    <Route name="feed" handler={NewsFeed}/>
  </Route>
</Route>
```

**Comment by tarjei** [comment] 2015-02-25 16:22
@mjackson but, then the route will have to have a unique URL, will it not? 

Today with 0.12.0 I got:
```
<Route name="courseFrame" handler={getPage("CourseFrame")} 
    path="/course/:courseName">
    <Route name="course-wrapper"  handler={getPage("CourseWrapper")} 
            path="/course/:courseName" >
        <Route name="course"  handler={getPage("CoursePage")} path="/course/:courseName" >
             <Route name="course-resource-modal"
                handler={getPage("ResourceModal")}
                path="/course/:courseName/videos/popup/*" />
        </Route>
        <Route name="course-users"  
            handler={getPage("UserListingPage")} 
            path="/course/:courseName/u/:role/?:numToShow?">
        </Route>
    </Route>
</Route>
```

My problem is that I do not want a unique url to match course-wrapper, but when I try to do that I get the error:
 Uncaught Error: Invariant Violation: You cannot nest pathxx inside "/course/:courseName/course-wrapper"; the parent requires URL parameters

This worked very well in 0.12.0.

**Comment by mjackson** [comment] 2015-02-25 16:29
> but, then the route will have to have a unique URL

No. In the first example that I have the `Dashboard` will be rendered at the `/` URL. Similarly, in the second example the `Inbox` will be rendered at `/`. We nested more UI without adding anything to the URL.

To get your example to work all you need to do is drop the `path` attribute from your `course-wrapper` element. When a route doesn't have a `path` it reuses its parent's `path`. You actually need less code :)

**Comment by mjackson** [comment] 2015-02-25 16:35
@tarjei Just looking over the rest of your route config ... you can also drop the `/course/:courseName` path from your `course` route and the `/course/:courseName/` prefix from your `course-resource-modal` and `course-users` routes.

The invariant is in place to prevent people from nesting e.g. a `/home` route inside a `/users/:userID` URL. Since the `/home` route has an absolute URL path, it doesn't build upon its parent. In this case, the parent still needs the `userID` param which is absent from the `/home` URL, so this is an error.

But in your case you were just using absolute URL paths that included the initial portion of their parent's path. We could probably issue a warning about that to make it more clear that you don't need to repeat the parent's path.

**Comment by mjackson** [comment] 2015-02-25 16:41
In fact, I'll reopen until we can get a warning in place.

**Comment by mjackson** [comment] 2015-02-25 17:11
Actually, instead of a warning I think we'll just silently allow your route config. There's nothing wrong with the fact that it's more verbose than it needs to be.

**Closed** 2015-02-25 17:17 UTC

**Comment by tarjei** [comment] 2015-02-25 19:52
Thanks for fantastic support!

**Comment by tarjei** [comment] 2015-02-25 21:02
@mjackson I got this to work:
```
<Route name="courseFrame" handler={getPage("CourseFrame")} path="/course/:courseName">
                <Route name="course-wrapper"  handler={getPage("CourseWrapper")} >
                    <Route name="course"  handler={getPage("CoursePage")} >
                         <Route name="course-resource-modal"
                            handler={getPage("ResourceModal")}
                            path="videos/popup/*" />
                    </Route>
                    <Route name="course-users"  
                        handler={getPage("UserListingPage")} 
                        path="u/:role/?:numToShow?">
                    </Route>
                </Route>
            ...
```

But the url to the course route ends up looking like this:
```
/course/testkurs-230/course-wrapper/course

```
I just want it to be /course/testkurs-230

Is that possible?

**Comment by mjackson** [comment] 2015-02-25 22:57
@tarjei You could remove the `name="course-wrapper"` and `name="course"` attributes. In that case, both of those routes will simply use the parent's path. If you need them to have names (because e.g. you're using them in a `<Link to="course">` you can just use `path=""` on both of them.

**Comment by tarjei** [comment] 2015-02-26 05:19
Ah, ok. Thanks :)

2015-02-25 23:57 GMT+01:00 Michael Jackson <notifications@github.com>:

> @tarjei <https://github.com/tarjei> You could remove the
> name="course-wrapper" and name="course" attributes. In that case, both of
> those routes will simply use the parent's path. If you need them to have
> names (because e.g. you're using them in a <Link to="course"> you can
> just use path="" on both of them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rackt/react-router/issues/867#issuecomment-76079796>.
>



-- 
__________________
Tarjei Huse
Mobil: 920 63 413

**Comment by dfoverdx** [comment] 2015-04-13 16:54
Sorry, I read through this, but I'm still confused.

I have the following (which is different from anything above):

    <Route name="app" path="/" handler={App}>
        <Route name="hud" handler={Hud} toonName='Ivellios'>
            <Route name="toon" handler={Toon} />
            <Route name="spell-book" handler={SpellBook} />
            <Route name="on-your-turn" handler={OnYourTurn} />
            <Route name="battle" handler={Battle} />
            <DefaultRoute handler={SpellBook} />
        </Route>

        <Route name="dashboard" handler={Dashboard}>
        </Route>

        <DefaultRoute handler={Hud} />
    </Route>

The idea is that the url `/` will default to `Hud` and `/hud` defaults to `SpellBook`, so `/` is the equivalent of `/hud/spellbook`.  However, that's not what's happening.  It's only rendering the `Hud` react class, which does make sense to me since that's the handler--and not the path--that I'm specifying.

How would I go about doing what I mean to do?
