### ISSUE TITLE
When aborting page transitions, the wrong URL is displayed in the address bar

### ISSUE THREAD

**Issue by rps** [rackt/react-router#2537] opened 2015-11-12 20:28 UTC
If a page transition is aborted when ```routerWillLeave``` returns ```false```, the address bar still shows the destination URL instead of the current URL. Test this by adding a ```routerWillLeave``` method to a component that only returns ```false``` and trying to navigate away. The page will stay the same but the URL will change.

Additional information: this occurred on a deeply nested component ("C" in A -> B -> C) that received its RouteContext from Route component "A".

**Comment by taion** [comment] 2015-11-12 20:29
Thanks for reporting this. Would you be able to put together a failing test case? We currently don't have any coverage at all on confirming navigation - it'd be nice to get a start.

**Comment by mjackson** [comment] 2015-11-12 20:35
We've actually got pretty decent tests around confirming navigation in the history project, which is where this issue should probably be filed (unless, for some reason, it's a bug in `useRoutes`). See, for example, [this test](https://github.com/rackt/history/blob/e3c9d5bb04fb10ddaa32cf940fe2dbc0a8604bf1/modules/__tests__/describeTransitions.js#L119-L154) that ensures the location does not change when the user does not confirm the transition.

**Comment by taion** [comment] 2015-11-12 20:55
It could be a bug in `listenBeforeLeavingRoute` here - that's actually what I was referring to, since that entire code path has no test coverage here, and it might very well have subtle bugs. I think it's the biggest coverage miss in router testing right now.

**Comment by taion** [comment] 2015-11-19 16:49
Actually, I think this is a history bug.

If you pull up the transitions example at http://localhost:8080/transitions/form, update the text input, hit the back button, then hit cancel, at least against Chrome 48, the URL in the omnibar will change, but the transition will be cancelled.

**Comment by rps** [comment] 2015-11-19 18:29
@taion In Chrome 46, in the Form example, the URL behaves as expected (e.g. the canceled transition causes the URL to revert back to "Form")

**Comment by taion** [comment] 2015-11-19 19:41
How were you triggering the transition?

**Comment by rps** [comment] 2015-11-19 19:50
By clicking Back or by clicking Dashboard

**Comment by taion** [comment] 2015-11-19 20:13
Here's a recipe for reproducing it:

1. Load the transitions example
2. Click on "Form"
3. Refresh the page
4. Hit the "back" button
5. Click "cancel"

This leaves me with:

![image](https://cloud.githubusercontent.com/assets/3112159/11282948/0fd865e4-8ed0-11e5-81b0-227d6131bf7d.png)

**Comment by rps** [comment] 2015-11-19 23:22
Interesting. Looks like it's the Refresh causing issues. ```routerWillLeave``` also isn't being called on refresh, as I expect it's intended to

**Comment by taion** [comment] 2015-11-20 14:23
@rps Can you reproduce your reported issue here with the transitions example?

**Comment by taion** [comment] 2015-11-26 20:35
I can't reproduce the original reported issue with the transitions example, even if I nest the transition hook. Closing for now until we can get a repro.

**Closed by taion** 2015-11-26 20:35 UTC
Labels: bug

**Comment by imdoge** [comment] 2017-08-31 03:04
Is this bug fixed in v2.8.1?
