### ISSUE TITLE
Firefox rendering wrong URL

### ISSUE THREAD

**Issue by taurose** [rackt/react-router#837] opened 2015-02-14 04:48 UTC
Steps to reproduce:

1. On Firefox, go to http://react-router-mega-demo.herokuapp.com/
2. Click any contact name
3. Focus URL bar, press enter
4. Click back button

Expected: URL path and content match up (either root or contact)
Actual: URL path is '/', but contact is rendered

Not sure about other browsers.

Apparently, this is due to browser back forward caching which can be disabled with

`window.unload = function() { }`

Is this worth documenting or even fixing?

**Comment by julen** [comment] 2015-02-24 08:50
I'm on Firefox and cannot reproduce this issue.

**Comment by BerkeleyTrue** [comment] 2015-02-24 15:28
Working fine for me on FF 35.0.1

**Comment by taurose** [comment] 2015-02-24 18:54
That's weird. I tried it on several machines (all windows though) and all of them were affected.

Here's a gif: http://i.giphy.com/AxVvjHQiDubQvpgcJW.gif

Are you sure that doesn't happen on your machines?

**Comment by BerkeleyTrue** [comment] 2015-02-24 19:51
Just upgraded to FF 36 on OSX Yosemite.
![rr-ffbug](https://cloud.githubusercontent.com/assets/6775919/6357655/d5d7b8be-bc1a-11e4-9d81-b9e7b1c4f319.gif)

but FF dev ed 37.0a2
![rr-ffbug-2](https://cloud.githubusercontent.com/assets/6775919/6357712/4b08c8a8-bc1b-11e4-8734-185048746e5e.gif)

**Comment by julen** [comment] 2015-02-24 22:29
37.0a2 here on OS X as well, but all working fine.

**Comment by ryanflorence** [comment] 2015-06-16 16:56
@taurose I can't reproduce this either, let me know if you track it down, closing until then.

**Comment by taurose** [comment] 2015-06-21 00:52
Still an issue (FF 38.0.5, Windows 8). Not sure why you can't reproduce this. Maybe the URL bar thing isn't consistent across platforms. Try this:

1. On Firefox, go to http://react-router-mega-demo.herokuapp.com/
2. Click any contact
3. Click `Ryan Florence` at the top to leave the app
4. Go **two** entries back at once by right clicking the back button

You should see the contact rendered, but the URL of the index page.

As far as I can tell [BFCache](https://developer.mozilla.org/en-US/docs/Working_with_BFCache) is the problem. It caches the whole DOM of the app at the state it was left, but then restores it even if we reenter at a different URL. And popstate/hashchange doesn't fire, so the app doesn't catch up.

As explained in the link above, I think we'd have to listen to some extra event. We can also suppress the cache, but would be nice to take advantage of it.

**Comment by ryanflorence** [comment] 2015-09-08 20:48
ping @taurose, do you know if this is resolved on master?

**Comment by ryanflorence** [comment] 2015-09-09 17:44
closing, I think `history` fixed this stuff, please reopen if I'm wrong.

**Closed by ryanflorence** 2015-09-09 17:44 UTC

**Comment by taurose** [comment] 2015-09-10 02:37
Not yet, but there's an open issue https://github.com/rackt/history/issues/34
