### ISSUE TITLE
Renders <noscript> tag when clicking <Link> using catch-all route.

### ISSUE THREAD

**Issue by dennis-van-bennekom** [rackt/react-router#1322] opened 2015-06-16 12:55 UTC
Hey!

This are my routes currently:

```javascript
export default (
	<Route path="/">
		<DefaultRoute handler={Main} />
        <Route path="*" handler={Main} />
	</Route>
);
```

I am using the <Link> tags like so:

```javascript
<Link to={this.props.menu[menuItem]} className="ps-fg-color-hover">
    {menuItem}
</Link>
```

When I click the link it created all I get is this:
```html
<div id="react-root">
    <noscript data-reactid=".tnbb9lc2dc"></noscript>
</div>
```

Any idea how/why this happens?

Thanks!

EDIT:
When I do a full refresh it does render correctly with server side rendering too. But when I click a link it goes to the blank page with the <noscript> tag.

EDIT2:
The weird thing is that the url does change but it doesn't seem to call the ```Main``` render method or even componentWillMount method at all.

**Comment by ryanflorence** [comment] 2015-06-16 16:38
You have no routes to link to.

Add some actual routes and link to them. I'm confident there is no bug in `Link` so I'm closing the issue, if you identify a bug let me know and I'll reopen :)

**Closed by ryanflorence** 2015-06-16 16:38 UTC

**Comment by andyengle** [comment] 2015-11-02 00:12
@dennis-van-bennekom FWIW, I ran into this same problem just now using react-router 1.0.  The paths existed, but still the ```<noscript>``` stuff was showing up in my DOM.  As it turns out, the problem I had was how I was importing.

wrong:
```javascript
import Link from 'react-router';
```

right:
```javascript
import {Link} from 'react-router';
```

You're probably well past this error by now, but thought I'd throw in this note in case anyone else encounters the same problem.  Thanks!

**Comment by jeron-diovis** [comment] 2015-11-05 11:37
Have a similar issue. I'm using server side rendering, as it's described in your [manual](https://github.com/rackt/react-router/blob/master/docs%2Fguides%2Fadvanced%2FServerRendering.md).
On client side Router is rendered as like this:
```jsx
ReactDOM.render(<Router routes={...} />);
```

And I have React's warning about different markup rendered, when markup from client side is just `<noscript></noscript>`.

After removing server-side rendering exactly same code on client side renders normally.

I have no idea what's going on, please help.

**Comment by jeron-diovis** [comment] 2015-11-05 12:32
Okay, I got it.
Here is the reason: https://github.com/rackt/react-router/blob/master/modules%2FRouter.js#L90-L91

That is, on first render `<Router>` is **always** `null` (which is converted to `<noscript>`). And exactly this `null` is to be synced with server-rendering markup.

So, to make it work, I did this:
```jsx
const routerHistory = useRoutes(createHistory)({ routes });

routerHistory.listen((err, state) => {
  if (err) {
    throw err;
  }
  ReactDOM.render(
    <RoutingContext {...state} history={routerHistory} 
    document.getElementById("container")
  );
});
```
completely dropping usage of `<Router>` on client-side too.

It is how it should be?

If yes, you definitely need to update guide about server rendering and describe this explicitly.

**Comment by igorpreston** [comment] 2015-12-08 22:43
Having the same problem. Please describe explicitly how we are supposed to handle server-side rendering and client-side rendering with react-router together?

**Comment by timdorr** [comment] 2015-12-08 23:13
@igorpreston It's documented: https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md

**Comment by igorpreston** [comment] 2015-12-08 23:29
@timdorr using exactly this code along with this on client:

```
const history = createBrowserHistory();

export default ReactDOM.render(<Router history={history} routes={routes}/>, document.getElementById('reactapp'));
```

and it still gives <noscript> error, saying that:
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <noscript data-reacti
 (server) <div data-reactid=".2
```

**Comment by timdorr** [comment] 2015-12-09 00:02
Normally that is caused by having multiple versions of React running on the page. Check your module tree.

**Comment by taion** [comment] 2015-12-09 00:05
You need to run `match` on the client side. See https://github.com/rackt/react-router/issues/2036.

There's a full example demonstrating this on rackt/async-props.
