### ISSUE TITLE
Link as custom element for navigations

### ISSUE THREAD

**Issue by carlitux** [rackt/react-router#2293] opened 2015-10-16 04:05 UTC
I need the li with the active class, there is way to do it?

```jsx
<li>
  <Link
    to='/list'
    aria-controls='list'
    activeClassName='active'
    >
    List
  </Link>
</li>
```

**Comment by edvinerikson** [comment] 2015-10-16 07:23
You should be able to do this with the [History](https://github.com/rackt/react-router/blob/master/docs/API.md#history-mixin) mixin.
Check out the [examples](https://github.com/rackt/react-router/blob/master/docs/API.md#examples-1).

**Comment by knowbody** [comment] 2015-10-16 10:36
thanks @edvinerikson 

@carlitux this is a duplicate of #2146 please search the issues first before creating the new one.

**Closed by knowbody** 2015-10-16 10:36 UTC
Labels: duplicate

**Comment by carlitux** [comment] 2015-10-16 12:39
@edvinerikson thank very much... @knowbody sorry I searched but I didn't read that.

**Comment by knowbody** [comment] 2015-10-16 15:21
@carlitux no problem :)
