### ISSUE TITLE
Using historyLocation a link to a # automatically pops back to the base url.

### ISSUE THREAD

**Issue by janpieterz** [rackt/react-router#1926] opened 2015-09-14 10:52 UTC
Using history location (history 1.9.0, react-router 1.0.0-rc1) creating a link to the right route <Link to="user#tab-1> doesn't actually direct the browser to user#tab-1 but back to user.

Seems like #1454 is a duplicate but closed. Any insights?

**Comment by ryanflorence** [comment] 2015-09-14 14:00
I believe this is a dupe of: https://github.com/rackt/history/pull/51 let me know if I'm wrong and we can reopen.

**Closed by ryanflorence** 2015-09-14 14:00 UTC

**Comment by janpieterz** [comment] 2015-09-14 14:36
Seems to be so, thanks! Looking forward to that change dropping in, for now I'll add it manually ;)
