### ISSUE TITLE
Router sets active class for root route always

### ISSUE THREAD

**Issue by drewhamlett** [rackt/react-router#1614] opened 2015-07-27 12:59 UTC
```
<Link to="/">Dashboard</Link>
<Link to="surveys">Surveys</Link>

ReactDOM.render((
  <Router history={history}>
    <Route component={App}>
      <Route name="dashboard" path="/" component={Dashboard} />
      <Route name="surveys" path="/surveys" component={Surveys} />
    </Route>
  </Router>
), document.getElementById('main'));
```

If I'm the dashboard route then just dashboard link gets active class.  If I'm on surveys, dashboard and surveys link gets active class.

**Comment by eXon** [comment] 2015-08-02 14:41
+1 got the same problem, my home page is always active

**Comment by nlutterman** [comment] 2015-08-24 04:04
I'm having this exact issue as well.  [mjackson](https://github.com/rackt/react-router/pull/1651#issuecomment-129265475) noted that it was fixed in the master branch.

**Comment by nlutterman** [comment] 2015-08-26 01:48
Hmm.

Actually, I just attempted this using master.  In my personal use case, it doesn't seem to be resolved.

    <Router history={history}>
        <Route component={app}>
            <Route name="home" path="/" component={Home} />
            <Route name="dashboard" path="dashboard" component={Dashboard} />
        </Route>
    </Router>

The "home" (`/`) link is still marked as active when having traversed to the `dashboard` path.

**Comment by nlutterman** [comment] 2015-08-26 12:24
@eXon & @drewhamlett 

I seem to have fixed it in the case of the master branch and in my case, which is similar to yours.  But I haven't been able to run the tests for it, yet.

Gonna clarify what my train of thought was:

I'm not clear on the absolute intent of the lines preceding this (there are calls to some functions `matchPattern()` and `compilePattern()` which effectively return an empty string and empty arrays for checking the path.

I fixed the issue by taking a look at [these lines](https://github.com/rackt/react-router/blob/master/modules/ActiveMixin.js#L22-L26)

When the `pathname` passed into that function is "/", then `PatternUtils.matchPattern()` returns a blank string as the `remainingPathname` that's used down the line.

Once it gets to this point:

```javascript
    if (remainingPathname === '') {
      return paramNames.every(function (paramName, index) {
        return String(paramValues[index]) === String(activeParams[paramName]);
      });
    }
```

...it will always return true if `paramNames` is empty.

The JavaScript function [`every()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every) checks to see if every element of an array passes a test of a given function.  The note to pay particular attention to is:

>every acts like the "for all" quantifier in mathematics. In particular, for an empty array, it returns true.

So, again, if there are no query parameters, then `true` is returned.

---

#### The Fix

I fixed the issue of the root route being active by changing the previous to this:

```javascript
    if (remainingPathname === '') {
        // Change this:
        // return paramNames.every(function (paramName, index) {
        // to this: 
        return paramNames.length > 0 && paramNames.every(function (paramName, index) {
        return String(paramValues[index]) === String(activeParams[paramName]);
      });
    }
```

So this seemed to fix it by short circuiting the `every()` tests and returning false if there are no params and `remainingPathname` is empty.

It *really* feels like I'm working around the actual problem instead though.  I'm pretty sure this isn't fixing it properly.

But yeah.  Change that in `lib/ActiveMixin.js` and it seems to work.

**Comment by gaearon** [comment] 2015-08-26 12:56
I think a PR with a failing test might help @mjackson get it fixed.

**Comment by nlutterman** [comment] 2015-08-26 20:49
I'll definitely do that and try to help.  Once I do some more digging and tested it, I'll submit one.  I'm 85% sure that I've changed the wrong thing.

**Comment by ameensol** [comment] 2015-09-04 04:24
+1 just ran into this as well

**Comment by knowbody** [comment] 2015-09-09 08:29
the PR I've sent a few days ago should fix that #1842

**Comment by ryanflorence** [comment] 2015-09-09 17:30
fixed in #1842

**Closed by ryanflorence** 2015-09-09 17:30 UTC

**Comment by nirajmchauhan** [comment] 2016-09-23 11:38
I am facing the same issue again.
```
ReactDOM.render((
	<Router history={browserHistory}>
		<Route path="/" component={Wrapper}>
			<IndexRoute path="/" component={Login}></IndexRoute>
			<Route path="/registration" name="registration" component={Registration}></Route>
		</Route>
	</Router>
	),
document.getElementById('app'));
```

My menu:
```
<li className="ui-component__primary-navigation-item">
  <Link to='/' activeClassName="active">Login</Link>
</li>
<li className="ui-component__primary-navigation-item">
  <Link to='/registration' activeClassName="active">Register</Link>
</li>
```

By default always I am getting active class on the first `li`

My current version is `v2.8.1`

**Comment by ohmattschwartz** [comment] 2016-09-29 14:48
Is there a regression, I'm experiencing this as well.

**Comment by nirajmchauhan** [comment] 2016-09-29 17:25
I have fixed and raised a pull request, waiting for reply now....

**Comment by lefterisk** [comment] 2016-10-07 10:47
It seems there is an alternative component to Link for exactly this use-case. 
`<IndexLink to='/' activeClassName="active">Login</IndexLink>`
works as expected

**Comment by wesharehoodies** [comment] 2016-10-27 14:09
@lefterisk This is exactly what I needed. Thanks!

**Comment by AlexFrazer** [comment] 2016-11-18 17:07
+1

**Comment by samuelmichaud** [comment] 2016-12-31 11:55
In case anyone got the same issue as mine...

The link component wasn't re-render because no props was given to it : 

```
App.js
  render(props) {
    return (
        <div className={props.children.props.name}>
          <Header path={props.children.props.path /*this props force re-render of header on each route change*/}/>
          {props.children}
        </div>
    )
  }

Header.js // nothing to do, component is re-render each time my route changes. The class active is properly applied.
const Header = () => (
<ul className="header">
        <li><Link to="/" activeClassName="active">Home</Link></li>
        <li><Link to="/contact" activeClassName="active">Contact</li>
</ul>
)

```

So everything works fine ;)

**Comment by callmenick** [comment] 2017-01-12 15:01
@lefterisk `IndexLink` solved it for me, thanks :)

**Comment by alonsogodinez** [comment] 2017-01-12 15:19
@lefterisk  Thank you so much! i think this might close this issue 😄

**Comment by sourvb** [comment] 2017-01-18 07:13
@lefterisk It solved my issue. You are awesome !!

**Comment by dotspencer** [comment] 2017-05-26 16:20
Use `<NavLink>` instead with the **exact** property, since `<IndexLink>` is not supported with RRv4.


    <NavLink exact to="/" activeClassName="current">...</NavLink>

**Comment by yasharma** [comment] 2017-09-29 15:49
I've also having the same issue
my setup is using
react-router-v4
react-router-redux-5

@samuelmichaud setting `activeClassName="active"` still not working for me
this is my setup - Header component
```javascript
<Nav>
	<LinkContainer to="/" activeClassName="active">
		<NavItem eventKey={1}>Home</NavItem>
    </LinkContainer>
    <LinkContainer to="/about">
		<NavItem eventKey={1}>About</NavItem>
    </LinkContainer>
    <LinkContainer to="/contact">
		<NavItem eventKey={1}>Contact</NavItem>
    </LinkContainer>
</Nav>
```
---- My Router Component
```javascript
<ConnectedRouter history={history}>
	<div>
		<Header />
		<Switch>
			<Route path="/" component={Main} />
	    	<Route path="/login" component={Login} />
	    	<Route path="/about" component={About} />
	    	<Route path="/contact" component={Contact} />
	    	<PrivateRoute path="/profile" component={Profile}/>
	  	</Switch>
  	</div>
</ConnectedRouter>
```
so for me following is working
```javascript
<Nav>
	<LinkContainer to="/" exact={true}>
		<NavItem eventKey={1}>Home</NavItem>
    </LinkContainer>
    <LinkContainer to="/about">
		<NavItem eventKey={1}>About</NavItem>
    </LinkContainer>
    <LinkContainer to="/contact">
		<NavItem eventKey={1}>Contact</NavItem>
    </LinkContainer>
</Nav>
```

**Comment by timdorr** [comment] 2017-09-29 18:24
@yasharma You need to use a <NavLink> for activeClassName.

**Comment by cesarvarela** [comment] 2018-01-20 03:13
2 things to solve this:

- use `withRouter` with your navigation component to trigger re-render
- set `exact={true}` if using the built-in `NavLink` component
