### ISSUE TITLE
Query provides same values for nextProps and this.props

### ISSUE THREAD

**Issue by anthonator** [rackt/react-router#2997] opened 2016-01-29 23:48 UTC
I'm attempting to check whether query values have changed in `componentWillReceiveProps`. However, when I compare `nextProps.location.query.whatever` to `this.props.location.query.whatever` the value is always the same.

I found [this (#584)](https://github.com/rackt/react-router/issues/584) issue which seemed to be the same/similar problem but it's quite old. I'm also using `react-router-redux` but I don't think the issue is there given I can interact with `react-router` directly and still have the same issues.

**Comment by taion** [comment] 2016-01-30 00:03
Check how many times your component is rendering – could be https://github.com/rackt/react-router-redux/issues/197.

**Comment by anthonator** [comment] 2016-01-30 00:15
If it's rendering multiple times should any of the times `componentWillReceiveProps` gets called have location objects that aren't identical?

If I'm at path: https://localhost:8080/someroute/somepath?somequery=1

and transition to: http://localhost:8080/someroute/somepath?somequery=2

and `componentWillReceiveProps` looks like:

```js
componentWillReceiveProps(nextProps) {
    let query        = this.props.location.query;
    let nextQuery = nextProps.location.query;

    console.log(query.somequery, nextQuery.somequery);
  }
```

the printed output is always: `2 2` no matter how many times it's called.

**Comment by taion** [comment] 2016-01-31 23:31
Can you reproduce this against one of our examples?

**Comment by taion** [comment] 2016-02-06 03:56
Please provide a repro.

**Comment by taion** [comment] 2016-02-07 20:15
Closing until we get some way to reproduce this.

**Closed by taion** 2016-02-07 20:15 UTC

**Comment by JeremyFossTemple** [comment] 2016-02-12 06:10
@anthonator  I've hit this issue too.   I've got two higher order components wrapping the actual component: connectToStores, and another one which (ideally) automatically triggers a fetch when it has detected a change in the props.

My query object looks like this:

`{
    foo: ["bar", "baz"],
    biz: { bam: ["boozle", "bogle"]}
}
`
As long as I only update foo I get the expected behavior of different old and new props in componentWillReceiveProps.  Biz is initially empty.  When I add bam: ["boozle"] to biz I get the expected behavior of different different old and new props.  But, on all subsequent modifications to biz I hit this issue and newProps === oldProps.  If I use the browser to navigate back and forth among the routes I've already pushed I do get different nextProps and previous props.

I spent a long time looking at this before I realized it was a non issue for me since I'm using datasource from alt-utils.  I was already using the local function to determine whether or not I needed to fetch.  Now I just trigger the fetch action every time.

**Comment by mvaivre** [comment] 2016-04-09 09:22
@anthonator : did you manage to fix this behaviour? I have a similar issue: `this.props.location.query.foo` and `nextProps.location.query.foo` are the same one out of two times when I change one query param repeatedly.

**Comment by mvaivre** [comment] 2016-04-10 15:44
I did a little repro: https://jsbin.com/culoxu/30/edit?js,console,output

I log `props` and `nextProps` in the parent `App` while a child is replacing the query.

**Comment by indapublic** [comment] 2017-03-24 12:45
+1

**Comment by indapublic** [comment] 2017-03-24 13:14
@mvaivre Do you found any solution?

**Comment by kud** [comment] 2017-09-27 16:10
I've got the same problem here.

```js
  componentWillReceiveProps(nextProps) {
    const { match } = this.props
    const { match: nextMatch } = nextProps

    if ( match.params.billId !== nextMatch.params.billId ) {
      // do something
    }
```

match and nextMatch are ALWAYS the same, even if I change the bill id in url.

**Comment by vannleonheart** [comment] 2017-11-16 16:20
Same with me, I assume this happened when using render on Route. The return component from this render function (on route) did not get the next props.

`
<Route match="/any" render={(nextProps) => <ComponentDidNotReceivedTheNextProps />} />
`

**Comment by jackson-sandland** [comment] 2018-02-22 21:45
Also seeing this issue. Passing in a prop from parent to child. `this.props === nextProps`

**Comment by inceddy** [comment] 2018-03-28 17:20
Same problem here. Any fix yet?

**Comment by SnowDiamond** [comment] 2018-04-05 11:24
I have some problem, this.props.location.query always equal to nextProps.location.query

**Comment by sstruct** [comment] 2018-05-03 03:56
@mvaivre Same here

**Comment by sstruct** [comment] 2018-05-03 03:58
@mvaivre Maybe you mixed context and props?

**Comment by etaybarzilay89** [comment] 2018-05-15 12:38
I also have the same issue.
this.props.match is not updated in componentWillReceiveProps when the url changes implicitly (not via history.push).
