### ISSUE TITLE
Cannot dispatch in the middle of a dispatch

### ISSUE THREAD

**Issue by jongbeau** [rackt/react-router#950] opened 2015-03-11 23:26 UTC
I'm running into an issue using react-router with alt.

From a Login react component, I have a login action that makes an API request and on successful response, it updates a SessionStore. The Login component sees the value of the session store updated through it's props passed down from the parent component, and in shouldComponentUpdate, it does a transitionTo (using react-router) to an account page. The account page then calls an action to update the SessionStore with a URL segment in componentWillMount.

I'm getting this error message:
Uncaught Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.

I believe it's due to the account page trying to update the SessionStore as the result of the SessionStore just getting updated from a previous action. Any suggestions on how to architect this differently?

NOTE: things work when using react-router's HashLocation, but not with the HistoryLocation.

**Comment by zupzup** [comment] 2015-03-20 14:53
Hey,

I ran into a similar issue some time ago. The problem is, that you are still in the same call stack as your first action, when the second action is triggered, because transitionTo is synchronous.

It works with HashLocation, as it sets the hash directly and asynchronously waits for the hash-change event.

To make it work with HistoryLocation, try to use an asynchronous version of transitionTo (just call it in a ``window.setTimeout(func, 0)``).

Another way would be to extend the Router.Navigation Mixin with asynchronous versions of the transition methods. Maybe something like this:

```javascript
let Navigation = assign({}, Router.Navigation, {
    transitionToAsync() {
        let args = Array.prototype.slice.apply(arguments);
        setImmediate(() => {
            this.context.router.transitionTo.apply(this, args);
        });
    },

    replaceWithAsync() {
        let args = Array.prototype.slice.apply(arguments);
        setImmediate(() => {
            this.context.router.replaceWith.apply(this, args);
        });
    }
});
```

Hope this helps.

**Comment by gaearon** [comment] 2015-03-20 15:00
Can you call your action in `componentDidMount` instead?

**Comment by jongbeau** [comment] 2015-03-20 16:07
componentDidMount does not work either. The only solution that works for me is the setTimeout.

**Comment by gaearon** [comment] 2015-03-20 16:12
I see. I currently use [rAF batching](https://github.com/petehunt/react-raf-batching) which is always async so I don't have this issue in my app. It comes with its own complexity cost though.

**Comment by ryanflorence** [comment] 2015-03-25 16:58
`shouldComponentUpdate` seems like the wrong place to do a transition. I don't know enough to suggest a better spot, but that seems weird.

**Comment by dadambickford** [comment] 2015-03-27 09:31
Running into issues with this as well. `this.transitionTo('page')` throws the dispatch in a dispatch error, while `this.goBack()` works fine. Only issue with `this.goBack()` is that if I refresh the page then the router doesn't know where to `goBack()` to. The following code with @zupzup 's suggestion works:

```
componentDidMount: function () {
  var self = this;
  AppDispatcher.register(function(payload) {
    var action = payload.action;
    if (payload.source === 'ACTION' && action.actionType == 'action_success') {
      window.setTimeout(self.transitionBack, 0);
    }
  });
},
transitionBack: function () {
  this.transitionTo('page');
}
```

Always possible that I'm doing something silly that I'm overlooking since it's 2:30 in the morning :flushed:

**Comment by ryanflorence** [comment] 2015-06-16 20:57
I'm closing this since its unclear if this is something the router can change, I don't have my head wrapped around problem, but if somebody else can figure out what the router needs to do differently, I'd love to work it in.

**Closed by ryanflorence** 2015-06-16 20:57 UTC

**Comment by xpepermint** [comment] 2015-07-31 15:43
```js
setImmediate(() => {
   this.context.router.transitionTo('/login');
});
```
works so why not making `transitionTo` to always run within `setImmediate` (an option nextTick: true or smth)? I see related questions all over the internet so it would be nice to have a method that always works.

**Comment by th0r** [comment] 2015-08-01 08:47
@xpepermint You can easily solve this by wrapping `Router.run` callback with something like lodash's `_.delay` and avoid wrapping every `router.transitionTo` calls.

**Comment by xpepermint** [comment] 2015-08-01 08:49
@th0r Thanks, hum... good idea, but it's still a `hack`.

**Comment by th0r** [comment] 2015-08-01 08:52
@xpepermint Yes, but it's the most `true` and simple hack)

**Comment by xpepermint** [comment] 2015-08-01 08:53
@th0r true :).
