### ISSUE TITLE
Unmet Peer Dependency warning

### ISSUE THREAD

**Issue by Industrial** [rackt/react-router#2687] opened 2015-12-09 09:55 UTC
Hi.

```
$ npm i --save react-router
npm info it worked if it ends with ok
npm info using npm@3.5.1
npm info using node@v5.1.1
npm info attempt registry request try #1 at 10:52:40 AM
npm http request GET https://registry.npmjs.org/react-router
npm http 200 https://registry.npmjs.org/react-router
npm info retry fetch attempt 1 at 10:52:49 AM
npm info attempt registry request try #1 at 10:52:49 AM
npm http fetch GET https://registry.npmjs.org/react-router/-/react-router-1.0.2.tgz
npm http fetch 200 https://registry.npmjs.org/react-router/-/react-router-1.0.2.tgz
npm info attempt registry request try #1 at 10:52:52 AM
npm http request GET https://registry.npmjs.org/fsevents
npm http 304 https://registry.npmjs.org/fsevents
npm info lifecycle react-router@1.0.2~preinstall: react-router@1.0.2
npm info linkStuff react-router@1.0.2
npm info lifecycle react-router@1.0.2~install: react-router@1.0.2
npm info lifecycle react-router@1.0.2~postinstall: react-router@1.0.2

> react-router@1.0.2 postinstall /home/tom/Code/Code9/test-loopback/node_modules/react-router
> node ./npm-scripts/postinstall.js

test-loopback@1.0.0 /home/tom/Code/Code9/test-loopback
├── UNMET PEER DEPENDENCY history@1.13.x
└── react-router@1.0.2 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.5
npm WARN optional Skipping failed optional dependency /id-builder/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.5
npm WARN browserify-shim@2.0.10 requires a peer of browserify@>= 2.3.0 < 4 but none was installed.
npm WARN browserify-shim@2.0.10 requires a peer of browserify@>= 2.3.0 < 4 but none was installed.
npm WARN mongodb-core@1.2.26 requires a peer of kerberos@~0.0 but none was installed.
npm WARN react-router@1.0.2 requires a peer of history@1.13.x but none was installed.
npm WARN test-loopback@1.0.0 No license field.
npm info ok
```

**Comment by sspross** [comment] 2015-12-09 10:00
+1

**Comment by chentsulin** [comment] 2015-12-09 10:59
duplicate of #2682, #2681, just downgrade your history to "~1.13.x"

**Comment by timdorr** [comment] 2015-12-09 14:17
Make sure you're installing history@1.13.1. The peerDependencies changed for 1.0.2 to avoid some depreciation warnings.

**Closed** 2015-12-09 14:17 UTC

**Comment by Shanky007** [comment] 2015-12-20 01:52
I am not sure if this is related (am very new to Mean stak stuff !) , I get the following error when I run "npm install"-->

npm WARN EPEERINVALID mongodb-core@1.2.26 requires a peer of kerberos@~0.0 but none was installed.

The complete Stack trace is-->

D:\Workspace\TestProject>npm install
TestProject@0.0.0 D:\Workspace\TestProject
└─┬ method-override@2.0.2
  ├── methods@1.0.1
  ├── parseurl@1.0.1
  └── vary@0.1.0

npm WARN EPEERINVALID mongodb-core@1.2.26 requires a peer of kerberos@~0.0 but none was installed.

Would appreciate any ideas?

**Comment by es6Test** [comment] 2015-12-23 12:48
Why isn't this dependency added as default?
