### ISSUE TITLE
Scroll to top when clicking links (restore #121 for react-router 2)

### ISSUE THREAD

**Issue by boosh** [rackt/react-router#3037] opened 2016-02-06 13:26 UTC
Seems like the same issue as #121 exists again with v2. Is there a good reason it was dropped? Is it intentional for us to have to add
```
componentDidUpdate() {
  this.getDOMNode().scrollTop = 0 ;
},
```
to every component?

**Comment by taion** [comment] 2016-02-06 14:02
Dupe of a ton of other issues, search around.

**Closed by taion** 2016-02-06 14:02 UTC

**Comment by mjhamm75** [comment] 2016-02-24 13:33
Adding the `onUpdate` to your `router` stops you from having to add the event to each component
```
<Router onUpdate={() => window.scrollTo(0, 0)} history={history}>
        {routes}
</Router>
```

**Comment by protoEvangelion** [comment] 2017-03-03 20:08
@mjhamm75  Thank you!!!!!  I was having a lot of trouble finding a concise and correct answer for this. Much appreciated :)
