### ISSUE TITLE
Compatible with ReactTransitionGroup?

### ISSUE THREAD

**Issue by klase** [rackt/react-router#727] opened 2015-01-26 16:25 UTC
Does React Router work with ReactTransitionGroup? Maybe I'm missing something but no matter what I try the lifecycle hooks won't trigger on components associated with a route: http://jsfiddle.net/d2mnwqLj/3/

**Comment by gaearon** [comment] 2015-01-26 16:59
I think @natew may have expertise related to this.
See also: #543 

Please let me know if this helps (or not)!

**Comment by klase** [comment] 2015-01-26 18:29
Seems to be the same issue. I was going to try the The RouteHandler mixin but it doesn't seem to be publicly exposed in the bower build?

**Comment by gaearon** [comment] 2015-01-26 19:08
[It should be](https://github.com/rackt/react-router/blob/master/modules/index.js#L17).

**Comment by mjackson** [comment] 2015-01-26 19:10
We really, really need to cut a release. Master is too far ahead of 0.11.

**Comment by klase** [comment] 2015-01-26 19:34
It's not exposed in the global build on cdnjs which I was using. I'll try compiling myself but need to get my head around webpack first..

**Comment by gaearon** [comment] 2015-01-26 21:39
@klase You should be able to compile with `npm install && npm build-min`.

**Comment by klase** [comment] 2015-01-26 22:21
Thanks that worked like a charm. Still not able to solve the original issue though, the RouteHandlerMixin doesn't have the getRouteHandler function referred to in #543 ? Do I need to grab it from the pull request perhaps?

**Comment by gaearon** [comment] 2015-01-26 22:39
@klase I assume it is now called [`createChildRouteHandler`](https://github.com/rackt/react-router/blob/master/modules/RouteHandlerMixin.js#L41).

**Comment by klase** [comment] 2015-01-26 23:07
Cheers the lifecycle hooks now trigger but I get this warning every time I hit a route: "Warning: You are calling cloneWithProps() on a child with a ref. This is dangerous because you're creating a new child which will not be added as a ref to its parent."

**Comment by zkilgore** [comment] 2015-02-03 23:58
@ryanflorence @klase I'm seeing this warning as well. Possible issue with react version we're using?

**Comment by zkilgore** [comment] 2015-02-28 16:06
@digitaltoad @alexaivars I was working through this last night, and this is a basic implementation that works, albeit with a caveat I'll get to:
```
var TransitionGroup = React.addons.TransitionGroup;
var {RouteHandlerMixin, State} = require("react-router");

module.exports = React.createClass({

  mixins: [ RouteHandlerMixin, State ],

  getHandlerKey: function() {
    return this.getRoutes().reverse()[0].name;
  },

  render: function() {
    var key = this.getHandlerKey();
    return(
      <TransitionGroup>
        {this.createChildRouteHandler({key: key})}
      </TransitionGroup>
    );
  }
});
```

However with this implementation you lose the ability to access the `component` argument of the static lifecycle method `willTransitionFrom` on the handler. This is because the [RouteHandlerMixin](https://github.com/rackt/react-router/blob/master/modules/RouteHandlerMixin.js) mixes in responsibility for setting the component the method is passed with `_updateRouteComponent` when the handler mounts/updates. It tries to access the component that was created via the call to [`createChildRouteHandler`](https://github.com/rackt/react-router/blob/master/modules/RouteHandlerMixin.js#44) via `this.refs[REF_NAME]` ([`REF_NAME` is just a constant`](https://github.com/rackt/react-router/blob/master/modules/RouteHandlerMixin.js#5)). The problem is that React TransitionGroup blows this ref away internally as it takes ownership away from the RouteHandlerMixin'd component because of it's use of `cloneWithProps`.

I spent a bit coming up with a hacky solution that passes the `_updateRouteComponent` function as a prop to a modified TransitionGroup so that the TransitionGroup component updates the handler component on it's mount/update. If anyone is interested or needs this piece I can try and clean it up and post.

**Comment by LKay** [comment] 2015-03-09 09:33
Doesn't seem to be working. I tried the code above as well as using default handler and not the one from mixin. When the route is changing after calling `transitionTo` the content of the div which holds page content gets replaced and elements for transitions get duplicated. http://cl.ly/image/2T3w3H3r3m39

I want to keep the content of the previous rout untouched until transition to the new route ends. Is that possible?

**Comment by natew** [comment] 2015-03-09 16:41
@zkilgore In react 0.13 they added a new `cloneElement` that doesn't blow away the ref. Perhaps you could try patching TransitionGroup?

**Comment by zkilgore** [comment] 2015-03-10 20:19
@natew Thank you for the tip! Will spend some time upgrading soon and report back how it goes. I'm excited about `cloneElement`.

@LKay are you implementing [`componentWillEnter`](http://facebook.github.io/react/docs/animation.html#componentwillentercallback) and [`componentWillLeave`](http://facebook.github.io/react/docs/animation.html#componentwillleavecallback) on your handlers?

**Comment by LKay** [comment] 2015-03-12 01:40
@zkilgore I tried to implement these methods in the first handler for the route but the elements still get duplicated when transition starts.

**Comment by zkilgore** [comment] 2015-03-13 18:20
@LKay can you toss what you have in a gist and post it?

**Comment by duro** [comment] 2015-03-20 18:26
@LKay I'm also very interested in seeing this. I was able to get `ReactCSSTransitionGroup` to work, but for the life of me `ReactTransitionGroup` does not work.

**Comment by natew** [comment] 2015-03-20 18:39
Are you guys using the mixin rather than the `<RouteHandler />` component?

I'm not using TransitionGroup directly, but I have a component that is basically a re-implementation of it and it works well once you get rid of the component.

**Comment by duro** [comment] 2015-03-20 18:48
@natew Can you send a gist of your implementation?

**Comment by duro** [comment] 2015-03-20 18:49
@natew And are you using React 0.13 or 0.12?

**Comment by natew** [comment] 2015-03-20 19:04
@duro it would be hard to extract, but the usage is <ViewList> in reapp rather than TransitionGroup, and the ViewList's use the same ideas as transitiongroup (https://github.com/reapp/reapp-ui/blob/master/mixins/ViewListMixin.jsx#L96) but to be honest you guys are probably further into this than me as far as using transitiongroup.

For me I got transitions working only with the mixin, but both on 0.12 and 0.13.

**Comment by zkilgore** [comment] 2015-03-20 22:10
@duro here's a gist of pretty much what I'm doing (albeit faked). But these are the methods I implement on my handlers to make animations work.

https://gist.github.com/zkilgore/254307f7cd5c42579ed0

And I'm still on 0.12 but think it should be fine in 0.13 too.

**Comment by duro** [comment] 2015-03-20 23:37
@zkilgore Do you get this warning in your implementation:

```
Warning: You are calling cloneWithProps() on a child with a ref. This is dangerous because you're creating a new child which will not be added as a ref to its parent.
```

**Comment by zkilgore** [comment] 2015-03-21 00:31
I do get that, but it's not a huge deal, and though I haven't implemented
0.13 yet I know that there is a new clone method called cloneElement which
from what I've read will alleviate that.

One caveat is that you won't be able to use the component in the transition
hooks unless you modify the transition group code. I wrote about it in a
previous comment, and if that's an issue for you I can post something on
that too. Only reason I'm hesitant is that I did it pretty quickly in the
first place and was gonna refactor it soon anyway...

**Comment by duro** [comment] 2015-03-21 01:14
@zkilgore Yea, I have tested going back and forth between `TransitionGroup` and `CSSTransitionGroup`. When I use `CSSTransitionGroup` I have no problem, as soon as I switch to `TransitionGroup` I start getting that warning and things start breaking.

Switching between basic routes is fine. But if I try to switch to a Handler that expects props to merge down from the RouteHandler, that Handler never gets the props.

My main question here is, what is broken? React-Router? Or TransitionGroup? It seems like we are hacking around some incompatibility here, and I'm wondering who's incompatibility I should be focusing on.

**Comment by zkilgore** [comment] 2015-03-21 02:51
@duro can you post a gist of what you're working with in the case where it
breaks?

I don't think either of these components are broken (in fact they're both
awesome), but the way they use refs and keys and the fact that transition
group clobbers the handlers ref makes it a challenge. Take a look at the
source of these to see what I mean, they're both straightforward.

**Comment by LKay** [comment] 2015-03-21 03:47
@zkilgore @duro 
I was able to fix it somehow but I don't really know what caused the problem with cloning content of the component. The base structure gist is here https://gist.github.com/LKay/babc1186f9e37c3a04f0 

I was not using Mixin but just `<RouteHandler />` and have nested handlers in corresponding routes. The problem in my case was mainly because states changing in Flux structure in my app and it messed somehow with RouteHandler. I cleaned this up a little and problem disappeared.

**Comment by duro** [comment] 2015-03-21 04:22
@LKay your gist appears to be implementing CSSTransitionGroup and not the lower level TransitionGroup. Are you implementing componentWillEnter and componentWillLeave life cycle methods on your RouteHandlers?

**Comment by duro** [comment] 2015-03-23 21:01
@zkilgore Here is a gist of the files in question:

https://gist.github.com/duro/0d6d3ef4d5b53be5e1e7

The main problem seems to stem from views (aboutServiceCategory.js) that need to load data via a static method before they are rendered. Other pages (home.js, careers.js, aboutLanding.js) that don't have bootstrapped data work fine.

I understand that individually both these libraries kick ass. It's just the incompatibility between the two that has me frustrated.

Any ideas on what I may be doing wrong?

**Comment by zkilgore** [comment] 2015-03-24 19:46
@duro Is the problem that when you switch between the 'about service category' pages the transition lifecycle methods are not called? If that's the issue, the problem is the handler will have the same key (the leaf route name, so 'serviceDetail') and in the TransitionGroup's eyes that's component isn't leaving or entering. You could append the :category param to the key to combat this.

If that is not the issue, then could you describe what exactly you want to happen and what exactly is happening?

**Comment by duro** [comment] 2015-03-25 20:32
I am using a static dataFetcher for getting the data from the server that is needed for the view. This static method, or series of static methods are called before the new Handler is rendered. Then this data is sent down the component tree via props.

What seems to be happening is that as soon as I start using TransitionGroup, my components render functions get called twice for each transition. And secondly, as I begin clicking from view to view, eventually I get an error thrown that the props data is not found. Path to this error is very odd, yet repeatable. It seems that transitions from certain pages to other pages always result in the issue.

Here is the full source for my project:

https://github.com/zehnergroup/zg-site-frontend/tree/dev

And here is the deployed version:

http://zg-sitev3.zgdev1.com/

If you hit the deployed site, open up dev tools, and start clicking between pages and sub-pages you will get the error. Set a breakpoint at the start of the render function on any of these components, and you will see that props are not getting passed down to the components:

https://github.com/zehnergroup/zg-site-frontend/blob/dev/src/client/app/components/Work/Landing.js
https://github.com/zehnergroup/zg-site-frontend/blob/dev/src/client/app/components/Work/WorkDetail.js
https://github.com/zehnergroup/zg-site-frontend/blob/dev/src/client/app/components/About/ServiceCategory.js

Some other key modules to pay attention to are:

The top level RouteHandler, where TransitionGroup is implemented:
https://github.com/zehnergroup/zg-site-frontend/blob/dev/src/client/app/components/App.js

The Router.run implementation:
https://github.com/zehnergroup/zg-site-frontend/blob/dev/src/client/app/index.js

The router itself:
https://github.com/zehnergroup/zg-site-frontend/blob/dev/src/client/app/router.js

Rest assured, I have tested heavily, and when I switch back to CSSTransitionGroup, everything works perfectly. This only seems to be an issue with TransitionGroup.

**Comment by duro** [comment] 2015-04-01 23:17
I have upgraded everything to 0.13, and my problem now seems to be consistent. Props are not being passed down to newly created route handlers. If I move from a RouteHandler that needs to props, to a RouteHandler that needs props, the transition does not work.

**Comment by colinramsay** [comment] 2015-05-12 20:25
I managed to get this to work, finally:

https://gist.github.com/colinramsay/42d3dbd0316212d65161

**Comment by duro** [comment] 2015-05-12 21:02
I'll test this ASAP. If this works you are a God in my book.

**Comment by colinramsay** [comment] 2015-05-12 21:21
Note that I might not have had exactly the same issue as you, this is just super-basic usage. The whole discussion of React and React Router animations really needs some TLC at this point I think.

**Comment by gaearon** [comment] 2015-05-12 21:28
You might want to try the `next` branch, as it's API is different, and there's no `RouteHandler` anymore (children are injected as normal props). I don't know if it makes animations simpler, but it might.

**Comment by duro** [comment] 2015-05-19 18:25
@colinramsay I took a deeper look at your component. It seems to implement a similar approach to `ReactCSSTransitionGroup` which is already in the React core. I was always able to get that one working without problem. My challenge was getting the `componentDidEnter` and `componentWillLeave` to fire on the RouteHandlers themselves. This way I can use pure JS animations like the GreenSock animation library.

@gaearon Are there any upgrade notes for the `next` branch?

**Comment by duro** [comment] 2015-06-15 21:02
@gaearon I see the `next` branch is now deleted? Did the rewrite get merged, or was it discontinued?

**Comment by srph** [comment] 2015-06-15 21:08
It was [merged](https://github.com/rackt/react-router/pull/1158

**Closed** 2015-06-16 16:46 UTC
Labels: unverified
