### ISSUE TITLE
Static functions never triggered

### ISSUE THREAD

**Issue by jakemmarsh** [rackt/react-router#664] opened 2015-01-08 01:17 UTC
I'm using React 0.12.2, and react-router 0.11.6. My routes look like this:

```javascript
module.exports = (
  <Route handler={GlobalApp}>

    <DefaultRoute handler={LoginPage} />

    <Route handler={InnerApp}>
      <Route name="Explore" path="/explore" handler={ExplorePage} />
      <Route name="TrackSearch" path="/tracks/search" handler={TrackSearchPage} />
      <Route name="Playlists" path="/playlists" handler={PlaylistsPage} />
      <Route name="PlaylistSearch" path="/playlists/search" handler={PlaylistSearchPage} />
      <Route name="Playlist" path="/playlist/:slug" handler={PlaylistPage} />
      <Route name="CreatePlaylist" path="/create" handler={CreatePlaylistPage} />
      <Route name="Profile" path="/profile/:username" handler={ProfilePage} />
      <Route name="Settings" path="/settings" handler={SettingsPage} />
    </Route>

    <Route handler={OuterApp}>
      <Route name="Login" path="/login" handler={LoginPage} />
      <Route name="Register" path="/register" handler={RegisterPage} />
      <Route name="ForgotPassword" path="/forgot" handler={ForgotPasswordPage} />
      <Route name="ResetPassword" path="/reset/:userId/:key" handler={ResetPasswordPage} />
      <NotFoundRoute handler={LoginPage} />
    </Route>

  </Route>
);
```

and my router looks like this:
```javascript
Router.run(routes, Router.HistoryLocation, function(Handler, state) {
  React.render(<Handler params={state.params} query={state.query} />, document.getElementById('app'));
});
```

This works fine, all my pages load and navigate correctly and as I intended. However, the statics functions `willTransitionTo` and `willTransitionFrom` never get called. First, I was trying it in an 'AuthenticatedRoute' mixin like this:

```javascript
var AuthenticatedRouteMixin = {
  statics: {
    willTransitionTo: function (transition) {
      console.log('will transition');
    }
  }
};
```

Then, I just tried a very simple one (below) directly on my handlers. I tried placing this on a top-level handler, such as `InnerApp`, as well as inner pages such as `PlaylistsPage`. None of these worked.

```javascript
statics: {
    willTransitionTo: function(transition) {
      console.log('will transition to', transition);
    }
  },
```

any ideas?

**Comment by gaearon** [comment] 2015-01-08 01:23
What do you do to cause navigation?

**Comment by jakemmarsh** [comment] 2015-01-08 01:24
There's a variety of things that cause navigation, but it's all directly via the router. Through either `<Link />`, `this.TransitionTo()`, or `this.ReplaceWith()`.

**Comment by gaearon** [comment] 2015-01-08 01:26
Might be worth putting a breakpoint here:

https://github.com/rackt/react-router/blob/v0.11.6/modules/utils/Transition.js#L82

and taking a look at `hooks`

**Comment by jakemmarsh** [comment] 2015-01-08 01:57
Done, but not exactly sure what to be looking for here? Here's what it looks like:

![screen shot 2015-01-07 at 8 57 00 pm](https://cloud.githubusercontent.com/assets/2916671/5656760/cb81e866-96af-11e4-9830-2979e159e1a5.png)

**Comment by jakemmarsh** [comment] 2015-01-08 05:54
I currently have a `willTransitionTo` static hook on every single route handler in my original post, and none of them are getting triggered

**Comment by gaearon** [comment] 2015-01-08 05:56
Yeah I got it, just want to understand the issue better. If you add a transition hook to `GlobalApp`, does it get called?

**Comment by jakemmarsh** [comment] 2015-01-08 05:57
Sorry, I meant that I have them on `GlobalApp`, `InnerApp`, and `OuterApp` now as well! Still nothing =/

**Comment by gaearon** [comment] 2015-01-08 12:22
Sorry, I don't understand what's going on there. Can you reproduce this with a smaller example?

**Comment by bitmage** [comment] 2015-01-14 20:31
I am also setting a static hook that is not getting called.  In my case it's a `willTransitionFrom` hook.  I have set that static property on my view, through a mixin.

Debugging the code, I have verified that the view appears in the [list of fromRoutes](https://github.com/rackt/react-router/blob/master/modules/utils/createRouter.js#L379).  When the check runs to see [if the handler has a willTransitionFrom property](https://github.com/rackt/react-router/blob/master/modules/utils/Transition.js#L15), that is returning undefined.  However, if I check `components[index].willTransitionFrom`, that *is* defined.

The handler is a function that looks like this:

```javascript
function (config, children) {
    // This factory should not be called when JSX is used. Use JSX instead.
    if ("production" !== "development") {
      warnForLegacyFactoryCall();
    }
    return factory.apply(this, arguments);
}
```

I don't see how or why this function would include the static properties of my view.  So my suspicion is that we are checking the wrong place for this property.  However, when I forked the project and tried to change `handler` to `components[index]`, the tests blew up quite magnificently.  So I'm not sure what's going on here.

I would definitely appreciate some insight on this, as it's blocking me on my current project.

**Comment by bitmage** [comment] 2015-01-14 20:52
Ok... nevermind.  My problem was that I did not use the `statics` key.  I missed that when reading [the documentation](https://github.com/rackt/react-router/blob/master/docs/api/components/RouteHandler.md#static-lifecycle-methods).

Another question:  When can we expect to see the refactor from promises to callbacks as an NPM publish?  I'm one of those strange people that prefers callbacks, so I'm excited about that.  :-)

**Comment by bitmage** [comment] 2015-01-15 00:16
Also, the work that I want to do inside these functions almost always relates to the state of the component.  Why are we defining these as static methods only to pass the component as an argument?  It would seem more idiomatic (and convenient) for `willTransitionFrom` to be an instance method.

**Comment by mjackson** [comment] 2015-01-25 02:10
@bitmage Callbacks will be released shortly in version 0.12. `willTransitionFrom` is a static method just for parity with `willTransitionTo`. Instead of having `willTransitionTo` be static (of necessity) and `willTransitionFrom` be instance-level, we just make them both static and give you the component in `willTransitionFrom`.

**Comment by mjackson** [comment] 2015-01-25 02:12
@jakemmarsh Can you reproduce the problem you're having in a smaller example? We have a ton of unit tests around transition hooks, so it's most likely a problem with your code somewhere.

**Comment by bitmage** [comment] 2015-02-10 00:52
@mjackson Ah, that does make sense.  You're saying willTransitionTo has to be static because the instance doesn't exist yet at the time you need to call it.

**Comment by ezmiller** [comment] 2015-02-13 16:26
I'm having a similar problem. When I try to load the DefaultRoute component or Link components like so:

```
var Router = require('react-router');
var DefaultRoute = Router.DefaultRoute;
var Link = Router.Link;
var Route = Router.Route;
var RouteHandler = Route.Handler;
```

If I step through the code in my debugger, the DefaultRoute, Link, and Route variables all end up containing the following:

```
function (config, children) {
    // This factory should not be called when JSX is used. Use JSX instead.
    if ("production" !== "development") {
      warnForLegacyFactoryCall();
    }
    return factory.apply(this, arguments);
  }
```

Farther down the line, I end up with an error:
>  Uncaught TypeError: Cannot read property '_mockedReactClassConstructor' of undefined

Does anyone know what I may be doing wrong here?

**Comment by gaearon** [comment] 2015-02-13 16:28
@ezmiller Make sure you don't have a separate React inside `node_modules/react-router/node_modules/react`. Two Reacts on one page won't work together, this often causes weird issues.

**Comment by ezmiller** [comment] 2015-02-13 17:16
Right! I don't think that's it thought. The package has react listed as a peerDependency (and not a dependency) in package.json, which is as it should be I think. I've run into that problem before as well.

**Comment by gaearon** [comment] 2015-02-13 17:21
This happens when people install router first, then react.

**Comment by ezmiller** [comment] 2015-02-13 17:22
FyI, i'm using React v0.12.2 and React-Router v0.12.0.

**Comment by gaearon** [comment] 2015-02-13 17:30
Can you put up a reproducible example on Github?

**Comment by ezmiller** [comment] 2015-02-13 17:43
I will try. Might take a bit.

**Comment by ezmiller** [comment] 2015-02-14 01:13
@gaearon: https://github.com/ezmiller/react-router-problem

this seems to recreate the problem.

**Comment by gaearon** [comment] 2015-02-14 07:26
I have not taken a close look yet but I see you're trying to render root component both in main.jsx and in App.jsx and this is strange. You certainly don't need two different React.render calls.

**Comment by ezmiller** [comment] 2015-02-14 09:40
I don't quite follow. There is no "root" component. Do you mean the fact that there is a React.render call in main.jsx and then again within the Router.run callback?

**Comment by ezmiller** [comment] 2015-02-14 10:08
I think I understood what you meant, and reorganize the code so that I'm only calling React.render once in main.jsx through the Router.run method. I'm still, however, getting the same ugly error.

**Comment by taurose** [comment] 2015-02-14 15:53
One thing I noticed is that you forgot to import `LoginForm` in `Login.jsx`. But this should give you a reference error, not the one you mentioned.

**Comment by ezmiller** [comment] 2015-02-14 18:47
@taurose fixed those errors. good catch. still the same confusing error however. :(

**Comment by taurose** [comment] 2015-02-14 19:11
You still have it wrong :smile:

`var RouteHandler = Router.Handler;`

should be

`var RouteHandler = Router.RouteHandler;`

**Comment by mjackson** [comment] 2015-02-14 22:55
ok, so it basically looks like this issue is more of a request for support, which is fine, but I don't think there's any code that demonstrates there's a bug in our code or docs.

@jakemmarsh Can we close this? Or are you still having the same problem? If so, can you post a minimal example that shows us what's broken?

**Comment by ezmiller** [comment] 2015-02-15 00:19
My problem is resolved, and it was a bug. The problem was as @taurose identified, that I'd not defined RouteHandler correctly. It was a typo in the end! 

The broader issue seems to be the totally opaque nature of this error message, which made the problem seem entirely more complicated than it was. But that may be an issue for React in general.

**Comment by globexdesigns** [comment] 2015-04-20 15:28
I'm having this will when used in combination with partial-app-loading (https://github.com/rackt/react-router/blob/master/examples/partial-app-loading/app.js). Because the Route's handler is created programmatically it seems as though the static methods inside my React views are not accessible by the React Router.

**Comment by ryanflorence** [comment] 2015-06-16 02:30
just tried reproducing this on current master, and it appears all transition hooks are working as designed, let me know if you find any issues.

**Closed by ryanflorence** 2015-06-16 02:30 UTC
Labels: unverified
