### ISSUE TITLE
Mismatching of rendered handler and corresponding path

### ISSUE THREAD

**Issue by th0r** [rackt/react-router#1027] opened 2015-03-31 07:53 UTC
I've made the reproduction repo: https://github.com/th0r/react-router-bug
Clone it, run `npm i && npm start`, open browser console, go to `http://localhost:8080/a` do the following:
 1. Click `To B` link
 2. Click `To A` link
 3. Quickly press browser's back button twice

Result: current location is `http://localhost:8080/a`, but the text on page is `B component` (route handler for path `/b`).

**Comment by taurose** [comment] 2015-03-31 20:24
Thanks. Can reproduce.

As far as I can tell, the problem is that when quickly going A->B->A the router skips the dispatch and thus the run callback of the last A, since A is still the currently rendered path.

**Comment by gaearon** [comment] 2015-04-01 12:03
Good one. I've had this in production but wasn't sure if it's a bug in router or my app.

**Comment by ryanflorence** [comment] 2015-06-17 02:58
closing, follow #1031

**Closed by ryanflorence** 2015-06-17 02:58 UTC
