### ISSUE TITLE
1.0.0-beta4 in npm doesn't have lib/BrowserHistory

### ISSUE THREAD

**Issue by davidpelayo** [rackt/react-router#1844] opened 2015-09-08 08:02 UTC
When installing the beta4 version from npm package manager, I can't include the BrowserHistory module because it hasn't been downloaded from npm:

```javascript
import BrowserHistory from 'react-router/lib/BrowserHistory';
```

Should the npm package files be updated?

**Comment by knowbody** [comment] 2015-09-08 08:06
duplicate of #1455 
and [here](https://github.com/rackt/react-router/issues/1455#issuecomment-138295614) is the answer for your question

**Comment by davidpelayo** [comment] 2015-09-08 08:34
Great. Installed, but how to use it properly now?

I had it before like:
```javascript
import BrowserHistory from 'react-router/lib/BrowserHistory';
/** Something else ***/
const history = new BrowserHistory();
/** Something else **/
<Provider store={store}>
  {() => <Routing {...{history, store}}/> }
</Provider>
```

**Comment by knowbody** [comment] 2015-09-08 08:40
the way @gaearon mentioned [here](https://github.com/rackt/react-router/issues/1455#issuecomment-138295614):

```js
import { createHistory } from 'history'; // you need to install this package
let history = createHistory();
```

**Comment by davidpelayo** [comment] 2015-09-08 08:48
Then I get the same error as [here](https://github.com/rackt/react-router/issues/1455#issuecomment-125165156)
```javascript
Uncaught Error: Invariant Violation: A <Router> needs a valid Location
```

**Comment by knowbody** [comment] 2015-09-08 09:04
it is hard for me to debug your code without seeing it. Here is a good and up to date example you can have a look at https://github.com/ironbay/react-redux-template

and here the [History docs](https://github.com/rackt/history/blob/master/docs/GettingStarted.md) that I mentioned above.

**Comment by davidpelayo** [comment] 2015-09-08 09:06
Ok thanks. I'm using redux, react-redux, react-router and redux-react-router.

**Closed** 2015-09-08 09:09 UTC

**Comment by stowns** [comment] 2015-09-13 16:45
i'm having similar issues including createBrowserHistory with rc1. 

Error: Cannot find module 'history/lib/createBrowserHistory'

```
import createHistory from 'history/lib/createBrowserHistory'
let browserHistory = createHistory();
```

Browserify just can't seem to resolve  'history/lib/createBrowserHistory' since it appears to be a submodule. Worked previously as:

```
import { history } from 'react-router/lib/BrowserHistory';
```

**Comment by gaearon** [comment] 2015-09-13 17:46
>Adding the 'history' module to my package.json works for now.

That's exactly where `history` comes from. React Router doesn't make it appear in `node_modules`; you need to depend on it explicitly.
