### ISSUE TITLE
transitionTo() root path with query doesn't work

### ISSUE THREAD

**Issue by jedwards1211** [rackt/react-router#1248] opened 2015-06-02 17:51 UTC
When I'm at `http://localhost:8000/#/login` 

and call 

`transitionTo('/?editChannel=1%2C10%2C1')`

the question mark disappears in the final URL:

`http://localhost:8000/#/editChannel=1%2C10%2C1`

react-router version 0.13.3

**Comment by mjackson** [comment] 2015-06-16 01:50
Can you please try this on current master (use `npm install react-router@beta`)? I'm unable to reproduce.

**Comment by mjackson** [comment] 2015-06-19 14:39
Pretty sure that whatever this is it's a duplicate of #1148. Let's follow up there.

**Closed by mjackson** 2015-06-19 14:39 UTC
Labels: unverified

**Comment by jedwards1211** [comment] 2015-06-20 00:24
Yup, looks like it.  Sorry, I hadn't had time yet to investigate on the beta.
I've been wishing for more documentation of exactly what one can put in `routeNameOrPath`.  I'd be happy to help write some if I can get someone to fact-check the intended (as opposed to de facto) behavior for me.
Thanks!
