### ISSUE TITLE
Inject router to the React 0.14 component

### ISSUE THREAD

**Issue by mvlach** [rackt/react-router#2305] opened 2015-10-17 18:09 UTC
Hi, after update to the react 0.14 I can't use the router.
```
RegisterComponent.contextTypes = {
    router: React.PropTypes.func.isRequired
};
```

the this.context.router is null..

Know somebody how to inject correctly the router ?

Thanks Mila

**Comment by chentsulin** [comment] 2015-10-17 18:43
duplicate of #1911 #1798 2064

**Closed** 2015-10-17 18:51 UTC
