### ISSUE TITLE
How to avoid random query string in the url?

### ISSUE THREAD

**Issue by boyarskiy** [rackt/react-router#2026] opened 2015-09-20 18:48 UTC
I have random query string in the url, something like <code>/#/?_k=m3j04n</code>. 
How can I avoid it?

**Comment by prattsj** [comment] 2015-09-20 18:59
Duplicate of https://github.com/rackt/react-router/issues/1967. Please check out the discussion and references to docs there.

**Closed by prattsj** 2015-09-20 18:59 UTC

**Comment by boyarskiy** [comment] 2015-09-20 19:07
@prattsj, thank you!
