### ISSUE TITLE
Unhandled URIError URI Malformed exception in HashLocation

### ISSUE THREAD

**Issue by thomPersson** [rackt/react-router#1286] opened 2015-06-11 07:57 UTC
If the URI is badly formatted for example _myRoutingApp/#/malformed%URI_ the call to decodeURI in [HashLocation.js](react-router/modules/locations/HashLocation.js) throws an URIError. 

I would like this exception to be handled and that the React Router redirects to the NotFoundRoute for example.

**Comment by mjackson** [comment] 2015-06-19 13:35
This is a duplicate of #1121. Let's follow up there.

**Closed by mjackson** 2015-06-19 13:35 UTC
Labels: bug
